package db.tools;

import java.io.FileInputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Properties;

/**
 * Minimal Oracle DDL runner for this repo.
 * - Reads jdbc.* from oracle.db.properties
 * - Creates TB_S_SIGNAL_EVENT + indexes
 *
 * Usage:
 *   javac -cp "WEBAPP_LIB_OJDBC" DbDdlRunner.java
 *   java  -cp ".:WEBAPP_LIB_OJDBC" db.tools.DbDdlRunner <path-to-oracle.db.properties>
 */
public class DbDdlRunner {

    public static void main(String[] args) throws Exception {
        if (args.length < 1) {
            System.err.println("Usage: DbDdlRunner <oracle.db.properties path>");
            System.exit(2);
        }

        String propPath = args[0];
        Properties p = new Properties();
        try (FileInputStream in = new FileInputStream(propPath)) {
            p.load(in);
        }

        String url = trim(p.getProperty("jdbc.url"));
        String user = trim(p.getProperty("jdbc.username"));
        String pass = trim(p.getProperty("jdbc.password"));

        if (url.isEmpty() || user.isEmpty()) {
            throw new IllegalStateException("Missing jdbc.url or jdbc.username in properties: " + propPath);
        }

        // Driver class is on classpath (ojdbc11.jar). DriverManager will auto-load, but load explicitly for clarity.
        try {
            Class.forName("oracle.jdbc.OracleDriver");
        } catch (Throwable t) {
            System.err.println("WARN: could not load oracle.jdbc.OracleDriver explicitly: " + t);
        }

        try (Connection c = DriverManager.getConnection(url, user, pass)) {
            c.setAutoCommit(true);
            System.out.println("Connected: " + safe(url) + " as " + user);

            createSignalEventTable(c);
            createIndex(c, "IX_TB_S_SIGNAL_EVENT_01", "CREATE INDEX IX_TB_S_SIGNAL_EVENT_01 ON TB_S_SIGNAL_EVENT (STOCK_CODE, EVENT_TIME)");
            createIndex(c, "IX_TB_S_SIGNAL_EVENT_02", "CREATE INDEX IX_TB_S_SIGNAL_EVENT_02 ON TB_S_SIGNAL_EVENT (SIGNAL_TYPE, EVENT_TIME)");
            createIndex(c, "IX_TB_S_SIGNAL_EVENT_03", "CREATE INDEX IX_TB_S_SIGNAL_EVENT_03 ON TB_S_SIGNAL_EVENT (TIMEFRAME, EVENT_TIME)");

            System.out.println("DONE");
        }
    }

    private static void createSignalEventTable(Connection c) throws SQLException {
        String ddl = "CREATE TABLE TB_S_SIGNAL_EVENT (\n" +
                "    EVENT_ID        NUMBER GENERATED BY DEFAULT AS IDENTITY,\n" +
                "    STOCK_CODE      VARCHAR2(20)   NOT NULL,\n" +
                "    COUNTRY_CODE    VARCHAR2(10)   DEFAULT 'KR' NOT NULL,\n" +
                "    TIMEFRAME       VARCHAR2(10)   NOT NULL,\n" +
                "    SIGNAL_TYPE     VARCHAR2(50)   NOT NULL,\n" +
                "    SIGNAL_GRADE    VARCHAR2(20)   DEFAULT 'INFO' NOT NULL,\n" +
                "    SCORE_DELTA     NUMBER         DEFAULT 0 NOT NULL,\n" +
                "    EVENT_TIME      DATE           NOT NULL,\n" +
                "    PRICE_REF       NUMBER,\n" +
                "    JSON_PARAMS     CLOB,\n" +
                "    MESSAGE         VARCHAR2(4000),\n" +
                "    SOURCE_JOB_ID   VARCHAR2(50),\n" +
                "    CREATE_DATE     DATE DEFAULT SYSDATE NOT NULL,\n" +
                "    CONSTRAINT PK_TB_S_SIGNAL_EVENT PRIMARY KEY (EVENT_ID)\n" +
                ")";

        execIgnoreExists(c, "TB_S_SIGNAL_EVENT", ddl);
    }

    private static void createIndex(Connection c, String name, String ddl) throws SQLException {
        execIgnoreExists(c, name, ddl);
    }

    private static void execIgnoreExists(Connection c, String objectName, String ddl) throws SQLException {
        try (Statement s = c.createStatement()) {
            s.execute(ddl);
            System.out.println("Created: " + objectName);
        } catch (SQLException e) {
            // ORA-00955: name is already used by an existing object
            if (e.getErrorCode() == 955) {
                System.out.println("Exists: " + objectName + " (skip)");
                return;
            }
            System.err.println("FAILED: " + objectName + " code=" + e.getErrorCode() + " state=" + e.getSQLState());
            throw e;
        }
    }

    private static String trim(String s) {
        return s == null ? "" : s.trim();
    }

    private static String safe(String url) {
        // do not print wallet path
        int i = url.indexOf("?TNS_ADMIN=");
        if (i > 0) return url.substring(0, i) + "?TNS_ADMIN=<redacted>";
        return url;
    }
}
