package db.tools;

import java.io.FileInputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Properties;

/**
 * Oracle DDL runner for WF-2-4 / WF-3-8 position tables.
 */
public class DbPositionDdlRunner {

    public static void main(String[] args) throws Exception {
        if (args.length < 1) {
            System.err.println("Usage: DbPositionDdlRunner <oracle.db.properties path>");
            System.exit(2);
        }

        String propPath = args[0];
        Properties p = new Properties();
        try (FileInputStream in = new FileInputStream(propPath)) {
            p.load(in);
        }

        String url = trim(p.getProperty("jdbc.url"));
        String user = trim(p.getProperty("jdbc.username"));
        String pass = trim(p.getProperty("jdbc.password"));

        if (url.isEmpty() || user.isEmpty()) {
            throw new IllegalStateException("Missing jdbc.url or jdbc.username in properties: " + propPath);
        }

        try {
            Class.forName("oracle.jdbc.OracleDriver");
        } catch (Throwable t) {
            System.err.println("WARN: could not load oracle.jdbc.OracleDriver explicitly: " + t);
        }

        try (Connection c = DriverManager.getConnection(url, user, pass)) {
            c.setAutoCommit(true);
            System.out.println("Connected: " + safe(url) + " as " + user);

            createPositionTables(c);
            System.out.println("DONE");
        }
    }

    private static void createPositionTables(Connection c) throws SQLException {
        execIgnoreExists(c, "TB_S_POSITION", "CREATE TABLE TB_S_POSITION ("
                + "POSITION_ID NUMBER GENERATED BY DEFAULT AS IDENTITY,"
                + "STOCK_GROUP VARCHAR2(30) NOT NULL,"
                + "STOCK_CODE VARCHAR2(20) NOT NULL,"
                + "MARKET_CODE VARCHAR2(10) DEFAULT 'KR' NOT NULL,"
                + "TOTAL_QTY NUMBER DEFAULT 0 NOT NULL,"
                + "AVG_PRICE NUMBER DEFAULT 0 NOT NULL,"
                + "CLOSE_FLAG VARCHAR2(1) DEFAULT 'N' NOT NULL,"
                + "STATE_CODE VARCHAR2(30) DEFAULT 'HOLD' NOT NULL,"
                + "LAST_TXN_ID NUMBER,"
                + "MODIFY_DATE DATE DEFAULT SYSDATE NOT NULL,"
                + "CREATE_USER VARCHAR2(50),"
                + "CREATE_DATE DATE DEFAULT SYSDATE NOT NULL,"
                + "CONSTRAINT PK_TB_S_POSITION PRIMARY KEY (POSITION_ID))");

        execIgnoreExists(c, "UX_TB_S_POSITION_01", "CREATE UNIQUE INDEX UX_TB_S_POSITION_01 ON TB_S_POSITION (STOCK_GROUP, STOCK_CODE)");
        execIgnoreExists(c, "IX_TB_S_POSITION_01", "CREATE INDEX IX_TB_S_POSITION_01 ON TB_S_POSITION (STOCK_GROUP, STOCK_CODE, CLOSE_FLAG)");
        execIgnoreExists(c, "IX_TB_S_POSITION_02", "CREATE INDEX IX_TB_S_POSITION_02 ON TB_S_POSITION (STOCK_CODE, MODIFY_DATE)");
        execIgnoreExists(c, "IX_TB_S_POSITION_03", "CREATE INDEX IX_TB_S_POSITION_03 ON TB_S_POSITION (STATE_CODE, CLOSE_FLAG, MODIFY_DATE)");

        execIgnoreExists(c, "TB_S_POSITION_TXN", "CREATE TABLE TB_S_POSITION_TXN ("
                + "TXN_ID NUMBER GENERATED BY DEFAULT AS IDENTITY,"
                + "POSITION_ID NUMBER,"
                + "STOCK_GROUP VARCHAR2(30) NOT NULL,"
                + "STOCK_CODE VARCHAR2(20) NOT NULL,"
                + "ACTION_TYPE VARCHAR2(20) NOT NULL,"
                + "QTY NUMBER DEFAULT 0 NOT NULL,"
                + "PRICE NUMBER DEFAULT 0 NOT NULL,"
                + "BEFORE_QTY NUMBER,"
                + "BEFORE_AVG NUMBER,"
                + "AFTER_QTY NUMBER,"
                + "AFTER_AVG NUMBER,"
                + "REASON_TEXT VARCHAR2(1000),"
                + "JSON_PARAMS CLOB,"
                + "CREATE_USER VARCHAR2(50),"
                + "CREATE_DATE DATE DEFAULT SYSDATE NOT NULL,"
                + "CONSTRAINT PK_TB_S_POSITION_TXN PRIMARY KEY (TXN_ID))");

        execIgnoreExists(c, "IX_TB_S_POSITION_TXN_01", "CREATE INDEX IX_TB_S_POSITION_TXN_01 ON TB_S_POSITION_TXN (STOCK_GROUP, STOCK_CODE, CREATE_DATE)");
        execIgnoreExists(c, "IX_TB_S_POSITION_TXN_02", "CREATE INDEX IX_TB_S_POSITION_TXN_02 ON TB_S_POSITION_TXN (POSITION_ID, CREATE_DATE)");
        execIgnoreExists(c, "IX_TB_S_POSITION_TXN_03", "CREATE INDEX IX_TB_S_POSITION_TXN_03 ON TB_S_POSITION_TXN (ACTION_TYPE, CREATE_DATE)");

        execIgnoreExists(c, "TB_S_POSITION_EVENT", "CREATE TABLE TB_S_POSITION_EVENT ("
                + "EVENT_ID NUMBER GENERATED BY DEFAULT AS IDENTITY,"
                + "POSITION_ID NUMBER,"
                + "STOCK_GROUP VARCHAR2(30),"
                + "STOCK_CODE VARCHAR2(20) NOT NULL,"
                + "EVENT_TYPE VARCHAR2(40) NOT NULL,"
                + "EVENT_LEVEL VARCHAR2(20) DEFAULT 'INFO' NOT NULL,"
                + "EVENT_TIME DATE DEFAULT SYSDATE NOT NULL,"
                + "MESSAGE VARCHAR2(4000),"
                + "JSON_PARAMS CLOB,"
                + "SOURCE_TXN_ID NUMBER,"
                + "CREATE_DATE DATE DEFAULT SYSDATE NOT NULL,"
                + "CONSTRAINT PK_TB_S_POSITION_EVENT PRIMARY KEY (EVENT_ID))");

        execIgnoreExists(c, "IX_TB_S_POSITION_EVENT_01", "CREATE INDEX IX_TB_S_POSITION_EVENT_01 ON TB_S_POSITION_EVENT (STOCK_CODE, EVENT_TIME)");
        execIgnoreExists(c, "IX_TB_S_POSITION_EVENT_02", "CREATE INDEX IX_TB_S_POSITION_EVENT_02 ON TB_S_POSITION_EVENT (POSITION_ID, EVENT_TIME)");
        execIgnoreExists(c, "IX_TB_S_POSITION_EVENT_03", "CREATE INDEX IX_TB_S_POSITION_EVENT_03 ON TB_S_POSITION_EVENT (EVENT_TYPE, EVENT_TIME)");
    }

    private static void execIgnoreExists(Connection c, String objectName, String ddl) throws SQLException {
        try (Statement s = c.createStatement()) {
            s.execute(ddl);
            System.out.println("Created: " + objectName);
        } catch (SQLException e) {
            if (e.getErrorCode() == 955) {
                System.out.println("Exists: " + objectName + " (skip)");
                return;
            }
            System.err.println("FAILED: " + objectName + " code=" + e.getErrorCode() + " state=" + e.getSQLState());
            throw e;
        }
    }

    private static String trim(String s) {
        return s == null ? "" : s.trim();
    }

    private static String safe(String url) {
        int i = url.indexOf("?TNS_ADMIN=");
        if (i > 0) return url.substring(0, i) + "?TNS_ADMIN=<redacted>";
        return url;
    }
}
