#KIS AppToken auto updated
#Fri Feb 27 13:17:44 KST 2026
kis.watchlist.domestic.realtime.enabled=false
kis.env=real
kis.account.no=6820546701
kis.rest.limit.per.second=20
kis.watchlist.quote.period.ms=500
kis.app.secret=DQsgBCi5yEJajPswCS8gY1ipi3UuRuHGfqBzyv2M9exvR1hx5fZhjWwL/Uhzv8QMB6NF0FSs7rerlCOG/6tPjWVuUrjSdAuCEUS4Ecw+Okaa+wI/t8jJ27eEZW/PMooZZ39njo0LDT/XHrkAOIYTJ9DQWLUkgaGlVafiDb8R3swRGqcuet4\=
kis.socket.limit.per.second=10
kis.app.tokenKey=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0b2tlbiIsImF1ZCI6IjdjYjBhOTRkLTZhNmQtNDdiNC1hOTYyLTk5ZGVjOTIxMjZmNiIsInByZHRfY2QiOiIiLCJpc3MiOiJ1bm9ndyIsImV4cCI6MTc3MjI1MjI2NCwiaWF0IjoxNzcyMTY1ODY0LCJqdGkiOiJQU0RuMXhzUkNvdE1KdUlnV0F3T2VMQTFTZ01tbkxoVVlZMlUifQ.3v8ynhWKWZUcjP9l8K4gfqX7uYL8vGCVaw9keCkuZj-kVou5yXj7KtRPkAq4AuMNTIiZ5y0K2yQILak6tBnIqA
kis.app.tokenExpire=20251204101530
kis.socket.host=ws\://ops.koreainvestment.com\:21000
kis.account.product.code=01
kis.app.tokenExpiredAt=2026-02-28 13\:17\:44
kis.http.host=https\://openapi.koreainvestment.com\:9443
kis.app.key=PSDn1xsRCotMJuIgWAwOeLA1SgMmnLhUYY2U
