#KIS AppToken auto updated
#Thu May 14 04:48:19 KST 2026
kis.ws.subscribe.min.interval.ms=100
kis.watchlist.domestic.realtime.enabled=true
kis.watchlist.quote.max.tokens.per.cycle=4
kis.env=real
kis.account.no=6820546701
kis.rest.limit.per.second=20
kis.watchlist.quote.period.ms=1000
kis.app.secret=DQsgBCi5yEJajPswCS8gY1ipi3UuRuHGfqBzyv2M9exvR1hx5fZhjWwL/Uhzv8QMB6NF0FSs7rerlCOG/6tPjWVuUrjSdAuCEUS4Ecw+Okaa+wI/t8jJ27eEZW/PMooZZ39njo0LDT/XHrkAOIYTJ9DQWLUkgaGlVafiDb8R3swRGqcuet4\=
kis.socket.limit.per.second=10
kis.watchlist.quote.fetch.pool.size=4
kis.app.tokenKey=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0b2tlbiIsImF1ZCI6IjkyMTRkYTZhLTk2NzMtNGViYS1iMTAxLTM0M2RhZGE0MWMxMyIsInByZHRfY2QiOiIiLCJpc3MiOiJ1bm9ndyIsImV4cCI6MTc3ODc4ODA5OSwiaWF0IjoxNzc4NzAxNjk5LCJqdGkiOiJQU0RuMXhzUkNvdE1KdUlnV0F3T2VMQTFTZ01tbkxoVVlZMlUifQ.lz_PIAm6911eMFAp5CjFWnWXiun0z52xf0zhTPEffnOVFa7b7Si6qHwIThlfu_R-5fGnSOgjenGwuPFRV2UkaQ
kis.app.tokenExpire=20251204101530
kis.socket.host=ws\://ops.koreainvestment.com\:21000
kis.ws.unsubscribe.min.interval.ms=100
kis.account.product.code=01
kis.ws.max.subscriptions=40
kis.app.tokenExpiredAt=2026-05-15 04\:48\:19
kis.http.host=https\://openapi.koreainvestment.com\:9443
kis.app.key=PSDn1xsRCotMJuIgWAwOeLA1SgMmnLhUYY2U
