-- TB_STK_MASTER 에 STK_TYPE 컬럼 추가
-- STK_TYPE: STOCK(일반종목) / ETF
-- KOSPI/KOSDAQ: 표준코드 KR3* 시작 → ETF, 나머지 → STOCK
-- NASDAQ/NYSE: 현재 secType=2(주식)만 파싱하므로 기본값 STOCK

ALTER TABLE TB_STK_MASTER ADD (
    STK_TYPE VARCHAR2(10) DEFAULT 'STOCK'
);

COMMENT ON COLUMN TB_STK_MASTER.STK_TYPE IS '종목구분: STOCK(일반종목) / ETF';

-- 기존 데이터 기본값 일괄 적용
UPDATE TB_STK_MASTER SET STK_TYPE = 'STOCK' WHERE STK_TYPE IS NULL;

COMMIT;
