-- WF-2-4 상태머신 임계값(-3%, +1%) 튜닝용 분석 쿼리
-- 목적: RISK_OFF / TREND_FOLLOW 분포와 성능을 빠르게 점검

-- 1) 이벤트 타입 분포(최근 30일)
SELECT EVENT_TYPE,
       COUNT(*) AS CNT
  FROM TB_S_POSITION_EVENT
 WHERE EVENT_TIME >= SYSDATE - 30
 GROUP BY EVENT_TYPE
 ORDER BY CNT DESC;

-- 2) 이벤트 타입별 평균 손익률(최근 30일)
-- json_params.pnL_pct 파싱(문자열 JSON에서 정규식 추출)
SELECT EVENT_TYPE,
       ROUND(AVG(TO_NUMBER(REGEXP_SUBSTR(JSON_PARAMS, '"pnl_pct":(-?[0-9]+\.?[0-9]*)', 1, 1, NULL, 1))), 4) AS AVG_PNL_PCT,
       MIN(TO_NUMBER(REGEXP_SUBSTR(JSON_PARAMS, '"pnl_pct":(-?[0-9]+\.?[0-9]*)', 1, 1, NULL, 1))) AS MIN_PNL_PCT,
       MAX(TO_NUMBER(REGEXP_SUBSTR(JSON_PARAMS, '"pnl_pct":(-?[0-9]+\.?[0-9]*)', 1, 1, NULL, 1))) AS MAX_PNL_PCT,
       COUNT(*) AS CNT
  FROM TB_S_POSITION_EVENT
 WHERE EVENT_TIME >= SYSDATE - 30
   AND JSON_PARAMS IS NOT NULL
 GROUP BY EVENT_TYPE
 ORDER BY CNT DESC;

-- 3) 임계값 경계구간 이벤트(튜닝 후보)
-- RISK_OFF 경계: -4% ~ -2%
-- TREND_FOLLOW 경계: 0% ~ +2%
WITH E AS (
    SELECT EVENT_ID,
           EVENT_TYPE,
           EVENT_TIME,
           STOCK_GROUP,
           STOCK_CODE,
           TO_NUMBER(REGEXP_SUBSTR(JSON_PARAMS, '"pnl_pct":(-?[0-9]+\.?[0-9]*)', 1, 1, NULL, 1)) AS PNL_PCT
      FROM TB_S_POSITION_EVENT
     WHERE EVENT_TIME >= SYSDATE - 30
       AND JSON_PARAMS IS NOT NULL
)
SELECT *
  FROM E
 WHERE (EVENT_TYPE = 'RISK_OFF' AND PNL_PCT BETWEEN -4 AND -2)
    OR (EVENT_TYPE = 'TREND_FOLLOW' AND PNL_PCT BETWEEN 0 AND 2)
 ORDER BY EVENT_TIME DESC;

-- 4) 종목별 이벤트 전이(최근 1000건)
SELECT STOCK_GROUP,
       STOCK_CODE,
       EVENT_TIME,
       EVENT_TYPE,
       LAG(EVENT_TYPE) OVER (PARTITION BY STOCK_GROUP, STOCK_CODE ORDER BY EVENT_TIME) AS PREV_EVENT
  FROM (
    SELECT *
      FROM TB_S_POSITION_EVENT
     ORDER BY EVENT_TIME DESC
     FETCH FIRST 1000 ROWS ONLY
  )
 ORDER BY STOCK_GROUP, STOCK_CODE, EVENT_TIME;
