-- 데모 데이터 정리 스크립트 (비파괴 범위: WF_TUNE_DEMO 그룹만)
DELETE FROM TB_S_POSITION_EVENT WHERE STOCK_GROUP = 'WF_TUNE_DEMO';
DELETE FROM TB_S_POSITION_TXN   WHERE STOCK_GROUP = 'WF_TUNE_DEMO';
DELETE FROM TB_S_POSITION       WHERE STOCK_GROUP = 'WF_TUNE_DEMO';
COMMIT;
