-- WF-2-4: 보유종목 관리 SEQUENCE 생성
-- TB_S_POSITION.POSITION_ID용 SEQUENCE

CREATE SEQUENCE TB_S_POSITION_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

-- 확인
SELECT TB_S_POSITION_SEQ.NEXTVAL FROM DUAL;
