CREATE TABLE TB_REC_SIGNAL (
    BASE_DT          DATE           NOT NULL,
    MKT_CD           VARCHAR2(10)   NOT NULL,
    STK_CD           VARCHAR2(20)   NOT NULL,
    STK_NM           VARCHAR2(100),
    CUR_PRICE        NUMBER(18,4),
    MON_OPEN_PRICE   NUMBER(18,4),
    MA5              NUMBER(18,4),
    MA20             NUMBER(18,4),
    MA60             NUMBER(18,4),
    MA120            NUMBER(18,4),
    MA240            NUMBER(18,4),
    GOLDEN_YN        CHAR(1),
    MON_UP_YN        CHAR(1),
    MON_CHG_RATE     NUMBER(18,4),
    TREND_STRENGTH   NUMBER(18,4),
    AVG_TRD_VAL_20   NUMBER(18,0),
    REC_YN           CHAR(1),
    REC_GRADE        VARCHAR2(1),
    REC_REASON       VARCHAR2(400),
    CREATED_AT       DATE DEFAULT SYSDATE,
    UPDATED_AT       DATE DEFAULT SYSDATE,
    CONSTRAINT PK_REC_SIGNAL PRIMARY KEY (BASE_DT, MKT_CD, STK_CD)
        USING INDEX LOCAL
)
PARTITION BY LIST (MKT_CD) (
    PARTITION P_KR VALUES ('KR'),
    PARTITION P_US VALUES ('US'),
    PARTITION P_ETC VALUES (DEFAULT)
);

COMMENT ON COLUMN TB_REC_SIGNAL.BASE_DT IS 'EFFECTIVE_BASE_DATE (실제 거래일 기준)';
COMMENT ON COLUMN TB_REC_SIGNAL.MKT_CD IS '시장그룹: KR / US';
COMMENT ON COLUMN TB_REC_SIGNAL.MON_OPEN_PRICE IS 'EFFECTIVE_YYYYMM 첫 거래일 ADJ_OPEN_PRICE';
COMMENT ON COLUMN TB_REC_SIGNAL.REC_GRADE IS '추천등급: A/B/C. REC_YN=N 이면 NULL 저장';
COMMENT ON COLUMN TB_REC_SIGNAL.AVG_TRD_VAL_20 IS '최근 20거래일 평균 거래대금';

CREATE INDEX IDX_REC_SIGNAL_YN
    ON TB_REC_SIGNAL (BASE_DT, MKT_CD, REC_YN)
    LOCAL;
