-- 목적: 추천/분석의 "설명가능성"과 백테스트/튜닝을 위한 신호 이벤트 이력 저장
-- 주의: 실제 적용(DDL 실행)은 DB 환경 확인 후 별도 수행
-- 대상 DB: Oracle (프로젝트 MyBatis SQL 스타일 기준)

-- 신호 이벤트 이력 테이블
-- - 종목별/타임프레임별 신호 발생 시점과 파라미터를 기록
-- - 저장 포맷을 통일하면 (추천 사유 노출, 백테스트, 디버깅)이 쉬워짐

CREATE TABLE TB_S_SIGNAL_EVENT (
    EVENT_ID        NUMBER GENERATED BY DEFAULT AS IDENTITY,
    STOCK_CODE      VARCHAR2(20)   NOT NULL,
    COUNTRY_CODE    VARCHAR2(10)   DEFAULT 'KR' NOT NULL,
    TIMEFRAME       VARCHAR2(10)   NOT NULL,  -- DAY | 30MIN | etc
    SIGNAL_TYPE     VARCHAR2(50)   NOT NULL,  -- 예: DAILY_TREND_OK, PULLBACK_REBOUND, BREAKOUT, BULLISH_MOMENTUM
    SIGNAL_GRADE    VARCHAR2(20)   DEFAULT 'INFO' NOT NULL, -- INFO|GOOD|WARN|BAD 등
    SCORE_DELTA     NUMBER         DEFAULT 0 NOT NULL,      -- 추천 점수에 기여한 가감점(선택)
    EVENT_TIME      DATE           NOT NULL,  -- 봉 기준 시각(일봉은 해당 일자, 30분봉은 캔들 시각)
    PRICE_REF       NUMBER,                  -- 신호 계산 기준가(종가/현재가 등)
    JSON_PARAMS     CLOB,                    -- 신호 파라미터(JSON 문자열). 예: {"ma20":...,"distPct":...}
    MESSAGE         VARCHAR2(4000),           -- 사람이 읽는 한 줄 요약(한글 가능)
    SOURCE_JOB_ID   VARCHAR2(50),             -- 배치 job_id
    CREATE_DATE     DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_TB_S_SIGNAL_EVENT PRIMARY KEY (EVENT_ID)
);

CREATE INDEX IX_TB_S_SIGNAL_EVENT_01 ON TB_S_SIGNAL_EVENT (STOCK_CODE, EVENT_TIME);
CREATE INDEX IX_TB_S_SIGNAL_EVENT_02 ON TB_S_SIGNAL_EVENT (SIGNAL_TYPE, EVENT_TIME);
CREATE INDEX IX_TB_S_SIGNAL_EVENT_03 ON TB_S_SIGNAL_EVENT (TIMEFRAME, EVENT_TIME);

-- 중복 방지(선택): 동일 종목/타임프레임/신호/시각에 대한 중복 입력이 걱정되면 유니크 제약을 고려
-- ALTER TABLE TB_S_SIGNAL_EVENT ADD CONSTRAINT UK_TB_S_SIGNAL_EVENT_01 UNIQUE (STOCK_CODE, TIMEFRAME, SIGNAL_TYPE, EVENT_TIME);
