CREATE TABLE TB_BATCH_EXEC_LOG (
    EXEC_ID      VARCHAR2(36)   NOT NULL,
    BATCH_ID     VARCHAR2(50)   NOT NULL,
    BASE_DT      DATE           NOT NULL,
    START_AT     DATE           NOT NULL,
    END_AT       DATE,
    STATUS       VARCHAR2(10),
    TOTAL_CNT    NUMBER(10),
    SUCCESS_CNT  NUMBER(10),
    FAIL_CNT     NUMBER(10),
    ERROR_MSG    VARCHAR2(2000),
    CREATED_AT   DATE DEFAULT SYSDATE,
    CONSTRAINT PK_BATCH_EXEC_LOG PRIMARY KEY (EXEC_ID)
);

COMMENT ON COLUMN TB_BATCH_EXEC_LOG.EXEC_ID IS '배치 실행 고유 ID (매 실행마다 신규 생성)';
COMMENT ON COLUMN TB_BATCH_EXEC_LOG.STATUS IS 'RUNNING: 실행중 / SUCCESS: 성공 / FAIL: 실패';

CREATE INDEX IDX_BATCH_LOG_DT
    ON TB_BATCH_EXEC_LOG (BASE_DT);
