CREATE TABLE TB_STK_MASTER (
    STK_CD         VARCHAR2(20)  NOT NULL,
    STK_NM         VARCHAR2(100),
    STK_NM_EN      VARCHAR2(200),
    MKT_CD         VARCHAR2(10),
    STK_STATUS     VARCHAR2(10),
    STK_TYPE       VARCHAR2(10)  DEFAULT 'STOCK',
    INDEX_CD       VARCHAR2(20),
    SECTOR_CD      VARCHAR2(6),
    MKT_CAP_SIZE   CHAR(1),
    PREF_YN        CHAR(1)  DEFAULT 'N' NOT NULL,
    SETTLE_MONTH   VARCHAR2(2),
    CURRENCY       VARCHAR2(10),
    LIST_DT        DATE,
    DELIST_DT      DATE,
    USE_YN         CHAR(1)  DEFAULT 'Y',
    CREATED_AT     DATE     DEFAULT SYSDATE,
    UPDATED_AT     DATE     DEFAULT SYSDATE,
    CONSTRAINT PK_STK_MASTER PRIMARY KEY (STK_CD)
);

COMMENT ON COLUMN TB_STK_MASTER.STK_NM IS '한글종목명';
COMMENT ON COLUMN TB_STK_MASTER.STK_NM_EN IS '영문종목명 (해외주식 .cod English name)';
COMMENT ON COLUMN TB_STK_MASTER.MKT_CD IS '상장 시장/거래소: KOSPI, KOSDAQ, NASDAQ, NYSE';
COMMENT ON COLUMN TB_STK_MASTER.STK_STATUS IS '종목상태: NORMAL/HALT/DELIST/CAUTION';
COMMENT ON COLUMN TB_STK_MASTER.STK_TYPE IS '종목구분: STOCK(일반종목) / ETF';
COMMENT ON COLUMN TB_STK_MASTER.INDEX_CD IS '주요지수 편입: KOSPI200, KOSDAQ150, SNP500, DOW (NULL=해당없음)';
COMMENT ON COLUMN TB_STK_MASTER.SECTOR_CD IS '업종대분류코드 (KOSPI/KOSDAQ .mst 지수업종대분류, 4자리)';
COMMENT ON COLUMN TB_STK_MASTER.MKT_CAP_SIZE IS '시가총액규모구분: 1=대형, 2=중형, 3=소형 (KOSPI/KOSDAQ)';
COMMENT ON COLUMN TB_STK_MASTER.PREF_YN IS '우선주여부: Y=우선주, N=보통주';
COMMENT ON COLUMN TB_STK_MASTER.SETTLE_MONTH IS '결산월 (01~12, KOSPI/KOSDAQ)';
COMMENT ON COLUMN TB_STK_MASTER.CURRENCY IS '통화코드 (해외주식: USD, HKD 등)';
COMMENT ON COLUMN TB_STK_MASTER.USE_YN IS '추천 대상 포함 여부: Y(포함) / N(제외)';
