CREATE TABLE TB_STK_DLY_PRICE (
    STK_CD           VARCHAR2(20)  NOT NULL,
    TRADE_DT         DATE          NOT NULL,
    RAW_OPEN_PRICE   NUMBER(18,4),
    RAW_HIGH_PRICE   NUMBER(18,4),
    RAW_LOW_PRICE    NUMBER(18,4),
    RAW_CLOSE_PRICE  NUMBER(18,4),
    ADJ_OPEN_PRICE   NUMBER(18,4),
    ADJ_HIGH_PRICE   NUMBER(18,4),
    ADJ_LOW_PRICE    NUMBER(18,4),
    ADJ_CLOSE_PRICE  NUMBER(18,4),
    VOLUME           NUMBER(18,0),
    TRADE_VALUE      NUMBER(18,0),
    ADJ_FACTOR       NUMBER(18,8),
    CREATED_AT       DATE DEFAULT SYSDATE,
    UPDATED_AT       DATE DEFAULT SYSDATE,
    CONSTRAINT PK_STK_DLY_PRICE PRIMARY KEY (STK_CD, TRADE_DT)
);

COMMENT ON COLUMN TB_STK_DLY_PRICE.ADJ_OPEN_PRICE IS '수정주가 시가 (저장 시점 보정형)';
COMMENT ON COLUMN TB_STK_DLY_PRICE.ADJ_CLOSE_PRICE IS '수정주가 종가 (저장 시점 보정형)';
COMMENT ON COLUMN TB_STK_DLY_PRICE.ADJ_FACTOR IS '수정 배율 (corporate action 기준)';

CREATE INDEX IDX_DLY_PRICE_DT
    ON TB_STK_DLY_PRICE (TRADE_DT);
