-- RecSignal / 공용 Batch Admin 스키마

CREATE TABLE TB_STK_BATCH_TASK_DEF (
    TASK_KEY            VARCHAR2(100)   NOT NULL,
    TASK_NAME           VARCHAR2(200)   NOT NULL,
    BEAN_NAME           VARCHAR2(200)   NOT NULL,
    ENABLED_YN          CHAR(1)         DEFAULT 'Y' NOT NULL,
    PARAM_SCHEMA_JSON   CLOB,
    DESCRIPTION         VARCHAR2(1000),
    REG_DT              DATE            DEFAULT SYSDATE NOT NULL,
    MOD_DT              DATE            DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_STK_BATCH_TASK_DEF PRIMARY KEY (TASK_KEY),
    CONSTRAINT CK_STK_BATCH_TASK_DEF_YN CHECK (ENABLED_YN IN ('Y','N'))
);

CREATE TABLE TB_STK_BATCH_JOB_DEF (
    JOB_ID               VARCHAR2(100)   NOT NULL,
    JOB_NAME             VARCHAR2(200)   NOT NULL,
    TASK_KEY             VARCHAR2(100)   NOT NULL,
    ENABLED_YN           CHAR(1)         DEFAULT 'Y' NOT NULL,
    TIMEZONE             VARCHAR2(60)    DEFAULT 'Asia/Seoul' NOT NULL,
    MAX_RUNTIME_SEC      NUMBER(10)      DEFAULT 7200 NOT NULL,
    ALLOW_MANUAL_RUN_YN  CHAR(1)         DEFAULT 'Y' NOT NULL,
    RUN_POLICY           VARCHAR2(20)    DEFAULT 'SINGLETON' NOT NULL,
    DESCRIPTION          VARCHAR2(1000),
    LAST_START_AT        DATE,
    LAST_END_AT          DATE,
    LAST_RESULT_CODE     VARCHAR2(20),
    LAST_RESULT_MSG      VARCHAR2(1000),
    REG_DT               DATE            DEFAULT SYSDATE NOT NULL,
    MOD_DT               DATE            DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_STK_BATCH_JOB_DEF PRIMARY KEY (JOB_ID),
    CONSTRAINT FK_STK_BATCH_JOB_DEF_TASK FOREIGN KEY (TASK_KEY)
        REFERENCES TB_STK_BATCH_TASK_DEF (TASK_KEY),
    CONSTRAINT CK_STK_BATCH_JOB_DEF_YN1 CHECK (ENABLED_YN IN ('Y','N')),
    CONSTRAINT CK_STK_BATCH_JOB_DEF_YN2 CHECK (ALLOW_MANUAL_RUN_YN IN ('Y','N')),
    CONSTRAINT CK_STK_BATCH_JOB_DEF_POLICY CHECK (RUN_POLICY IN ('SINGLETON'))
);

CREATE TABLE TB_STK_BATCH_JOB_SCHEDULE (
    SCHEDULE_ID          NUMBER(18)      NOT NULL,
    JOB_ID               VARCHAR2(100)   NOT NULL,
    SCHEDULE_TYPE        VARCHAR2(20)    NOT NULL,
    CRON_EXPR            VARCHAR2(120),
    INTERVAL_SEC         NUMBER(10),
    WINDOW_START_HH24MI  VARCHAR2(5),
    WINDOW_END_HH24MI    VARCHAR2(5),
    MISFIRE_POLICY       VARCHAR2(20)    DEFAULT 'SKIP' NOT NULL,
    ENABLED_YN           CHAR(1)         DEFAULT 'Y' NOT NULL,
    NEXT_RUN_AT          DATE,
    LAST_EVAL_AT         DATE,
    REG_DT               DATE            DEFAULT SYSDATE NOT NULL,
    MOD_DT               DATE            DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_STK_BATCH_JOB_SCHEDULE PRIMARY KEY (SCHEDULE_ID),
    CONSTRAINT FK_STK_BATCH_JOB_SCH_JOB FOREIGN KEY (JOB_ID)
        REFERENCES TB_STK_BATCH_JOB_DEF (JOB_ID) ON DELETE CASCADE,
    CONSTRAINT CK_STK_BATCH_SCH_TYPE CHECK (SCHEDULE_TYPE IN ('CRON','INTERVAL')),
    CONSTRAINT CK_STK_BATCH_SCH_YN CHECK (ENABLED_YN IN ('Y','N')),
    CONSTRAINT CK_STK_BATCH_SCH_MISFIRE CHECK (MISFIRE_POLICY IN ('SKIP','RUN_ONCE')),
    CONSTRAINT CK_STK_BATCH_SCH_RULE CHECK (
        (SCHEDULE_TYPE = 'CRON' AND CRON_EXPR IS NOT NULL AND INTERVAL_SEC IS NULL)
        OR
        (SCHEDULE_TYPE = 'INTERVAL' AND INTERVAL_SEC IS NOT NULL AND CRON_EXPR IS NULL)
    )
);

CREATE TABLE TB_STK_BATCH_JOB_PARAM (
    PARAM_ID             NUMBER(18)      NOT NULL,
    JOB_ID               VARCHAR2(100)   NOT NULL,
    PARAM_KEY            VARCHAR2(100)   NOT NULL,
    PARAM_VALUE          CLOB,
    PARAM_TYPE           VARCHAR2(20)    DEFAULT 'STRING' NOT NULL,
    REQUIRED_YN          CHAR(1)         DEFAULT 'N' NOT NULL,
    MASKED_YN            CHAR(1)         DEFAULT 'N' NOT NULL,
    REG_DT               DATE            DEFAULT SYSDATE NOT NULL,
    MOD_DT               DATE            DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_STK_BATCH_JOB_PARAM PRIMARY KEY (PARAM_ID),
    CONSTRAINT UK_STK_BATCH_JOB_PARAM UNIQUE (JOB_ID, PARAM_KEY),
    CONSTRAINT FK_STK_BATCH_PARAM_JOB FOREIGN KEY (JOB_ID)
        REFERENCES TB_STK_BATCH_JOB_DEF (JOB_ID) ON DELETE CASCADE,
    CONSTRAINT CK_STK_BATCH_PARAM_TYPE CHECK (PARAM_TYPE IN ('STRING','NUMBER','BOOLEAN','DATE','JSON')),
    CONSTRAINT CK_STK_BATCH_PARAM_YN1 CHECK (REQUIRED_YN IN ('Y','N')),
    CONSTRAINT CK_STK_BATCH_PARAM_YN2 CHECK (MASKED_YN IN ('Y','N'))
);

CREATE TABLE TB_STK_BATCH_JOB_RUNTIME (
    JOB_ID               VARCHAR2(100)   NOT NULL,
    RUNNING_YN           CHAR(1)         DEFAULT 'N' NOT NULL,
    LOCK_OWNER           VARCHAR2(200),
    LOCK_AT              DATE,
    LAST_HEARTBEAT_AT    DATE,
    STOP_REQUEST_YN      CHAR(1)         DEFAULT 'N' NOT NULL,
    CURRENT_EXEC_ID      VARCHAR2(36),
    MOD_DT               DATE            DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_STK_BATCH_JOB_RUNTIME PRIMARY KEY (JOB_ID),
    CONSTRAINT FK_STK_BATCH_RUNTIME_JOB FOREIGN KEY (JOB_ID)
        REFERENCES TB_STK_BATCH_JOB_DEF (JOB_ID) ON DELETE CASCADE,
    CONSTRAINT CK_STK_BATCH_RUNTIME_YN1 CHECK (RUNNING_YN IN ('Y','N')),
    CONSTRAINT CK_STK_BATCH_RUNTIME_YN2 CHECK (STOP_REQUEST_YN IN ('Y','N'))
);

-- 로그 보관 주기 설정 컬럼 추가 (0 또는 NULL이면 자동 삭제 안 함)
ALTER TABLE TB_STK_BATCH_JOB_SCHEDULE ADD (LOG_RETENTION_DAYS NUMBER(5) DEFAULT 30);

CREATE SEQUENCE SEQ_STK_BATCH_JOB_SCHEDULE START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_STK_BATCH_JOB_PARAM START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE INDEX IDX_STK_BATCH_TASK_DEF_01 ON TB_STK_BATCH_TASK_DEF (ENABLED_YN);
CREATE INDEX IDX_STK_BATCH_JOB_DEF_01 ON TB_STK_BATCH_JOB_DEF (ENABLED_YN, TASK_KEY);
CREATE INDEX IDX_STK_BATCH_JOB_SCH_01 ON TB_STK_BATCH_JOB_SCHEDULE (JOB_ID, ENABLED_YN, NEXT_RUN_AT);
CREATE INDEX IDX_STK_BATCH_JOB_PARAM_01 ON TB_STK_BATCH_JOB_PARAM (JOB_ID);
CREATE INDEX IDX_STK_BATCH_JOB_RUNTIME_01 ON TB_STK_BATCH_JOB_RUNTIME (RUNNING_YN, LOCK_AT);

-- 초기 Task Seed
INSERT INTO TB_STK_BATCH_TASK_DEF (TASK_KEY, TASK_NAME, BEAN_NAME, ENABLED_YN, DESCRIPTION)
VALUES ('REC_SIGNAL_RUN', 'RecSignal 배치 실행', 'recSignalRunTask', 'Y', 'RecSignalDailyBatch.run 위임');

COMMIT;
