CREATE OR REPLACE VIEW VW_S_RECO_PICK_STATS AS
SELECT
    E.EVAL_TYPE,
    E.HOLD_DAYS,
    P.SOURCE_MKT_CD,
    P.LISTING_MARKET,
    NVL(P.REC_GRADE, 'NA') AS REC_GRADE,
    NVL(P.ENTRY_RULE_CODE, 'NA') AS ENTRY_RULE_CODE,
    CASE
        WHEN NVL(P.TREND_STRENGTH, 0) < 1 THEN 'TS_LT_1'
        WHEN NVL(P.TREND_STRENGTH, 0) < 3 THEN 'TS_1_TO_3'
        WHEN NVL(P.TREND_STRENGTH, 0) < 5 THEN 'TS_3_TO_5'
        ELSE 'TS_GE_5'
    END AS TREND_BUCKET,
    CASE
        WHEN NVL(P.MON_CHG_RATE, 0) < 0 THEN 'MON_NEG'
        WHEN NVL(P.MON_CHG_RATE, 0) < 3 THEN 'MON_0_TO_3'
        WHEN NVL(P.MON_CHG_RATE, 0) < 7 THEN 'MON_3_TO_7'
        ELSE 'MON_GE_7'
    END AS MONTH_BUCKET,
    COUNT(*) AS SAMPLE_CNT,
    ROUND(AVG(CASE WHEN E.WIN_YN = 'Y' THEN 100 ELSE 0 END), 4) AS WIN_RATE,
    ROUND(AVG(CASE WHEN E.TP1_HIT_YN = 'Y' THEN 100 ELSE 0 END), 4) AS TP1_RATE,
    ROUND(AVG(CASE WHEN E.STOP_HIT_YN = 'Y' THEN 100 ELSE 0 END), 4) AS STOP_RATE,
    ROUND(AVG(E.RETURN_PCT), 4) AS AVG_RETURN_PCT,
    ROUND(AVG(E.MFE_PCT), 4) AS AVG_MFE_PCT,
    ROUND(AVG(E.MAE_PCT), 4) AS AVG_MAE_PCT
FROM TB_S_RECO_PICK P
JOIN TB_S_RECO_PICK_EVAL E
  ON E.PICK_ID = P.PICK_ID
WHERE E.CALC_STATUS = 'READY'
GROUP BY
    E.EVAL_TYPE,
    E.HOLD_DAYS,
    P.SOURCE_MKT_CD,
    P.LISTING_MARKET,
    NVL(P.REC_GRADE, 'NA'),
    NVL(P.ENTRY_RULE_CODE, 'NA'),
    CASE
        WHEN NVL(P.TREND_STRENGTH, 0) < 1 THEN 'TS_LT_1'
        WHEN NVL(P.TREND_STRENGTH, 0) < 3 THEN 'TS_1_TO_3'
        WHEN NVL(P.TREND_STRENGTH, 0) < 5 THEN 'TS_3_TO_5'
        ELSE 'TS_GE_5'
    END,
    CASE
        WHEN NVL(P.MON_CHG_RATE, 0) < 0 THEN 'MON_NEG'
        WHEN NVL(P.MON_CHG_RATE, 0) < 3 THEN 'MON_0_TO_3'
        WHEN NVL(P.MON_CHG_RATE, 0) < 7 THEN 'MON_3_TO_7'
        ELSE 'MON_GE_7'
    END;
