CREATE TABLE TB_BATCH_EXEC_ITEM_LOG (
    EXEC_ID       VARCHAR2(36)    NOT NULL,
    BATCH_ID      VARCHAR2(50)    NOT NULL,
    BASE_DT       DATE            NOT NULL,
    MKT_CD        VARCHAR2(10)    NOT NULL,
    STK_CD        VARCHAR2(20)    NOT NULL,
    STK_NM        VARCHAR2(100),
    ITEM_STATUS   VARCHAR2(10)    NOT NULL,
    ERROR_MSG     VARCHAR2(2000),
    CREATED_AT    DATE DEFAULT SYSDATE,
    UPDATED_AT    DATE DEFAULT SYSDATE,
    CONSTRAINT PK_BATCH_EXEC_ITEM_LOG PRIMARY KEY (EXEC_ID, STK_CD)
);

CREATE INDEX IDX_BATCH_EXEC_ITEM_01
    ON TB_BATCH_EXEC_ITEM_LOG (BATCH_ID, BASE_DT, MKT_CD, ITEM_STATUS);
