CREATE TABLE TB_STK_MON_PRICE (
    STK_CD           VARCHAR2(20)  NOT NULL,
    BASE_YM          VARCHAR2(6)   NOT NULL,
    ADJ_OPEN_PRICE   NUMBER(18,4),
    ADJ_HIGH_PRICE   NUMBER(18,4),
    ADJ_LOW_PRICE    NUMBER(18,4),
    ADJ_CLOSE_PRICE  NUMBER(18,4),
    VOLUME           NUMBER(18,0),
    TRADE_VALUE      NUMBER(18,0),
    CREATED_AT       DATE DEFAULT SYSDATE,
    UPDATED_AT       DATE DEFAULT SYSDATE,
    CONSTRAINT PK_STK_MON_PRICE PRIMARY KEY (STK_CD, BASE_YM)
);

COMMENT ON COLUMN TB_STK_MON_PRICE.ADJ_OPEN_PRICE IS '월시가: 해당월 첫 거래일 ADJ_OPEN_PRICE (참조용, 추천 계산 직접 사용 금지)';
