CREATE TABLE TB_S_RECO_PICK_DAILY (
    PICK_ID                  NUMBER          NOT NULL,
    TRADE_DT                 DATE            NOT NULL,
    MKT_CD                   VARCHAR2(10)    NOT NULL,
    STK_CD                   VARCHAR2(20)    NOT NULL,
    OPEN_PRICE               NUMBER(18,4),
    HIGH_PRICE               NUMBER(18,4),
    LOW_PRICE                NUMBER(18,4),
    CLOSE_PRICE              NUMBER(18,4),
    HOLD_DAY_NO_FROM_REC     NUMBER,
    HOLD_DAY_NO_FROM_WATCH   NUMBER,
    HOLD_DAY_NO_FROM_BUY     NUMBER,
    RETURN_FROM_REC_PCT      NUMBER(18,4),
    RETURN_FROM_WATCH_PCT    NUMBER(18,4),
    RETURN_FROM_BUY_PCT      NUMBER(18,4),
    MFE_FROM_REC_PCT         NUMBER(18,4),
    MAE_FROM_REC_PCT         NUMBER(18,4),
    MFE_FROM_BUY_PCT         NUMBER(18,4),
    MAE_FROM_BUY_PCT         NUMBER(18,4),
    UP_DOWN_FLAG             VARCHAR2(10),
    TP1_HIT_YN               CHAR(1),
    STOP_HIT_YN              CHAR(1),
    SELL_SIGNAL_CODE         VARCHAR2(30),
    SELL_SIGNAL_TEXT         VARCHAR2(1000),
    PRICE_SOURCE             VARCHAR2(20)    DEFAULT 'KIS_DAILY' NOT NULL,
    CREATE_DATE              DATE            DEFAULT SYSDATE NOT NULL,
    MODIFY_DATE              DATE            DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_TB_S_RECO_PICK_DAILY PRIMARY KEY (PICK_ID, TRADE_DT)
);

CREATE INDEX IX_TB_S_RECO_PICK_DAILY_01 ON TB_S_RECO_PICK_DAILY (STK_CD, TRADE_DT);
CREATE INDEX IX_TB_S_RECO_PICK_DAILY_02 ON TB_S_RECO_PICK_DAILY (SELL_SIGNAL_CODE, TRADE_DT);
