CREATE TABLE TB_TRADE_CALENDAR (
    TRADE_DT    DATE          NOT NULL,
    MKT_CD      VARCHAR2(10)  NOT NULL,
    TRADE_YN    CHAR(1),
    CREATED_AT  DATE DEFAULT SYSDATE,
    CONSTRAINT PK_TRADE_CALENDAR PRIMARY KEY (TRADE_DT, MKT_CD)
);

COMMENT ON COLUMN TB_TRADE_CALENDAR.MKT_CD IS '시장코드: KR / US';
COMMENT ON COLUMN TB_TRADE_CALENDAR.TRADE_YN IS 'Y: 거래일 / N: 휴장일';
