-- TB_STK_MASTER 상세정보 컬럼 추가
-- 그룹1: 공통 식별 / 그룹2: 해외종목 전용 / 그룹3: 국내 상세 (KOSPI/KOSDAQ/KONEX)

/* ── 그룹1: 공통 ─────────────────────────────── */
ALTER TABLE TB_STK_MASTER ADD SCRT_GRP_CLS_CD  VARCHAR2(10);  -- 증권그룹구분코드 (ST/ETF/EW/MF 등)
ALTER TABLE TB_STK_MASTER ADD SYMBOL            VARCHAR2(20);  -- 심볼 (해외종목 별도 심볼)

COMMENT ON COLUMN TB_STK_MASTER.SCRT_GRP_CLS_CD  IS '증권그룹구분코드: ST=주권 MF=투자회사 RT=부동산 SC=선박 DR=예탁증서 EW=ELW EF=ETF FS=외국주권';
COMMENT ON COLUMN TB_STK_MASTER.SYMBOL            IS '해외종목 심볼 (.cod Symbol 컬럼, 국내는 STK_CD와 동일)';

/* ── 그룹2: 해외종목 전용 ──────────────────────── */
ALTER TABLE TB_STK_MASTER ADD NATN_CD           VARCHAR2(2);   -- 국가구분코드
ALTER TABLE TB_STK_MASTER ADD EXCH_CD           VARCHAR2(10);  -- 거래소코드 (NAS/NYS 등)
ALTER TABLE TB_STK_MASTER ADD OVRS_BSTP_CD      VARCHAR2(10);  -- 해외업종분류코드
ALTER TABLE TB_STK_MASTER ADD DOW30_YN          CHAR(1);       -- 다우30 편입여부
ALTER TABLE TB_STK_MASTER ADD NAS100_YN         CHAR(1);       -- 나스닥100 편입여부
ALTER TABLE TB_STK_MASTER ADD SNP500_YN         CHAR(1);       -- S&P500 편입여부

COMMENT ON COLUMN TB_STK_MASTER.NATN_CD      IS '국가구분코드 (.cod National code, 해외종목 전용)';
COMMENT ON COLUMN TB_STK_MASTER.EXCH_CD      IS '거래소코드 (.cod Exchange code: NAS/NYS/HKS 등)';
COMMENT ON COLUMN TB_STK_MASTER.OVRS_BSTP_CD IS '해외업종분류코드 (.cod 업종분류코드)';
COMMENT ON COLUMN TB_STK_MASTER.DOW30_YN     IS '다우30 편입여부 Y/N (별도 소스 필요, .cod에 없음)';
COMMENT ON COLUMN TB_STK_MASTER.NAS100_YN    IS '나스닥100 편입여부 Y/N';
COMMENT ON COLUMN TB_STK_MASTER.SNP500_YN    IS 'S&P500 편입여부 Y/N';

/* ── 그룹3: 업종분류 ────────────────────────────── */
ALTER TABLE TB_STK_MASTER ADD BSTP_MEDM_DIV_CD  VARCHAR2(4);  -- 지수업종중분류코드
ALTER TABLE TB_STK_MASTER ADD BSTP_SMAL_DIV_CD  VARCHAR2(4);  -- 지수업종소분류코드

COMMENT ON COLUMN TB_STK_MASTER.BSTP_MEDM_DIV_CD IS '지수업종중분류코드 (KOSPI/KOSDAQ .mst 4자리)';
COMMENT ON COLUMN TB_STK_MASTER.BSTP_SMAL_DIV_CD IS '지수업종소분류코드 (KOSPI/KOSDAQ .mst 4자리)';

/* ── 그룹3: 지수편입 플래그 ──────────────────────── */
ALTER TABLE TB_STK_MASTER ADD KOSPI200_SECT_CD  CHAR(1);   -- KOSPI200 섹터업종코드 (0=미편입 1=건설 ... A=건강관리)
ALTER TABLE TB_STK_MASTER ADD KOSPI100_YN       CHAR(1);
ALTER TABLE TB_STK_MASTER ADD KOSPI50_YN        CHAR(1);
ALTER TABLE TB_STK_MASTER ADD KOSPI_YN          CHAR(1);   -- KOSPI지수 편입여부
ALTER TABLE TB_STK_MASTER ADD KOSDAQ150_YN      CHAR(1);   -- KOSDAQ150 편입여부 (코스닥 전용)
ALTER TABLE TB_STK_MASTER ADD KRX_YN            CHAR(1);
ALTER TABLE TB_STK_MASTER ADD KRX100_YN         CHAR(1);
ALTER TABLE TB_STK_MASTER ADD KRX300_YN         CHAR(1);
ALTER TABLE TB_STK_MASTER ADD KRX_CAR_YN        CHAR(1);   -- KRX자동차
ALTER TABLE TB_STK_MASTER ADD KRX_SMCN_YN       CHAR(1);   -- KRX반도체
ALTER TABLE TB_STK_MASTER ADD KRX_BIO_YN        CHAR(1);
ALTER TABLE TB_STK_MASTER ADD KRX_BANK_YN       CHAR(1);
ALTER TABLE TB_STK_MASTER ADD KRX_ENRG_CHMS_YN  CHAR(1);  -- KRX에너지화학
ALTER TABLE TB_STK_MASTER ADD KRX_STEL_YN       CHAR(1);   -- KRX철강
ALTER TABLE TB_STK_MASTER ADD KRX_MEDI_CMNC_YN  CHAR(1);  -- KRX미디어통신
ALTER TABLE TB_STK_MASTER ADD KRX_CNST_YN       CHAR(1);   -- KRX건설
ALTER TABLE TB_STK_MASTER ADD KRX_SCRT_YN       CHAR(1);   -- KRX증권
ALTER TABLE TB_STK_MASTER ADD KRX_SHIP_YN       CHAR(1);   -- KRX선박
ALTER TABLE TB_STK_MASTER ADD KRX_INSU_YN       CHAR(1);   -- KRX섹터_보험
ALTER TABLE TB_STK_MASTER ADD KRX_TRNS_YN       CHAR(1);   -- KRX섹터_운송
ALTER TABLE TB_STK_MASTER ADD SRI_YN            CHAR(1);   -- SRI (코스피)
ALTER TABLE TB_STK_MASTER ADD ETP_CLS_CD        CHAR(1);   -- ETP상품구분코드
ALTER TABLE TB_STK_MASTER ADD ELW_PBLC_YN       CHAR(1);   -- ELW발행여부 (코스피)
ALTER TABLE TB_STK_MASTER ADD SPAC_YN           CHAR(1);   -- 기업인수목적회사(SPAC)

COMMENT ON COLUMN TB_STK_MASTER.KOSPI200_SECT_CD  IS 'KOSPI200섹터업종 0=미편입 1=건설 2=중공업 3=철강소재 4=에너지화학 5=정보통신 6=금융 7=필수소비재 8=자유소비재 9=산업재 A=건강관리 B=커뮤니케이션';
COMMENT ON COLUMN TB_STK_MASTER.ETP_CLS_CD        IS 'ETP상품구분코드 0=해당없음 1=투자회사형 2=수익증권형 3=ETN 4=손실제한ETN 5=상장형수익증권';

/* ── 그룹3: 종목특성 ─────────────────────────────── */
ALTER TABLE TB_STK_MASTER ADD MNIN_YN           CHAR(1);   -- 제조업여부 (코스피)
ALTER TABLE TB_STK_MASTER ADD LOW_CURRENT_YN    CHAR(1);   -- 저유동성종목여부
ALTER TABLE TB_STK_MASTER ADD SPRN_NMIX_YN      CHAR(1);   -- 지배구조지수종목여부 (코스피)
ALTER TABLE TB_STK_MASTER ADD VENT_YN           CHAR(1);   -- 벤처기업여부 (코스닥 전용)
ALTER TABLE TB_STK_MASTER ADD INVT_CATN_YN      CHAR(1);   -- 투자주의환기종목여부 (코스닥 전용)

/* ── 그룹3: 거래경보 ─────────────────────────────── */
ALTER TABLE TB_STK_MASTER ADD SLTR_YN           CHAR(1);   -- 정리매매여부
ALTER TABLE TB_STK_MASTER ADD MANG_YN           CHAR(1);   -- 관리종목여부
ALTER TABLE TB_STK_MASTER ADD SHORT_OVER_CLS_CD CHAR(1);   -- 단기과열종목구분코드 0=해당없음 1=지정예고 2=지정 3=지정연장
ALTER TABLE TB_STK_MASTER ADD MRKT_ALRM_CLS_CD  VARCHAR2(2); -- 시장경고구분코드
ALTER TABLE TB_STK_MASTER ADD MRKT_ALRM_RISK_YN CHAR(1);  -- 시장경고위험예고여부
ALTER TABLE TB_STK_MASTER ADD INSN_PBNT_YN      CHAR(1);   -- 불성실공시여부
ALTER TABLE TB_STK_MASTER ADD BYPS_LSTN_YN      VARCHAR2(2); -- 우회상장여부
ALTER TABLE TB_STK_MASTER ADD FLNG_CLS_CD       VARCHAR2(2); -- 락구분코드
ALTER TABLE TB_STK_MASTER ADD FCAM_MOD_CLS_CD   VARCHAR2(2); -- 액면가변경구분코드
ALTER TABLE TB_STK_MASTER ADD ICIC_CLS_CD       VARCHAR2(3); -- 증자구분코드
ALTER TABLE TB_STK_MASTER ADD SSTS_HOT_YN       CHAR(1);   -- 공매도과열종목여부
ALTER TABLE TB_STK_MASTER ADD STANGE_RUNUP_YN   CHAR(1);   -- 이상급등종목여부

/* ── 그룹3: 신용/거래조건 ────────────────────────── */
ALTER TABLE TB_STK_MASTER ADD MARG_RATE         VARCHAR2(3);  -- 증거금비율
ALTER TABLE TB_STK_MASTER ADD CRDT_ABLE         CHAR(1);      -- 신용주문가능여부
ALTER TABLE TB_STK_MASTER ADD CRDT_DAYS         VARCHAR2(12); -- 신용기간
ALTER TABLE TB_STK_MASTER ADD CO_CRDT_LIMT_OVER_YN CHAR(1);  -- 회사신용한도초과여부
ALTER TABLE TB_STK_MASTER ADD SECU_LEND_ABLE_YN CHAR(1);     -- 담보대출가능여부
ALTER TABLE TB_STK_MASTER ADD STLN_ABLE_YN      CHAR(1);     -- 대주가능여부

/* ── 그룹3: 종목 기본수치 ────────────────────────── */
ALTER TABLE TB_STK_MASTER ADD STCK_SDPR         VARCHAR2(9);  -- 주식기준가
ALTER TABLE TB_STK_MASTER ADD FRML_MRKT_DEAL_QTY_UNIT VARCHAR2(5); -- 정규시장매매수량단위
ALTER TABLE TB_STK_MASTER ADD OVTM_MRKT_DEAL_QTY_UNIT VARCHAR2(5); -- 시간외시장매매수량단위
ALTER TABLE TB_STK_MASTER ADD PRDY_VOL          VARCHAR2(12); -- 전일거래량
ALTER TABLE TB_STK_MASTER ADD STCK_FCAM         VARCHAR2(12); -- 주식액면가
ALTER TABLE TB_STK_MASTER ADD LSTN_STCN         VARCHAR2(15); -- 상장주수(천)
ALTER TABLE TB_STK_MASTER ADD CPFN              VARCHAR2(21); -- 자본금
ALTER TABLE TB_STK_MASTER ADD PO_PRC            VARCHAR2(7);  -- 공모가격

/* ── 그룹3: 재무정보 ─────────────────────────────── */
ALTER TABLE TB_STK_MASTER ADD SALE_ACCOUNT      VARCHAR2(9);  -- 매출액
ALTER TABLE TB_STK_MASTER ADD BSOP_PRFI         VARCHAR2(9);  -- 영업이익
ALTER TABLE TB_STK_MASTER ADD OP_PRFI           VARCHAR2(9);  -- 경상이익
ALTER TABLE TB_STK_MASTER ADD THTR_NTIN         VARCHAR2(5);  -- 당기순이익
ALTER TABLE TB_STK_MASTER ADD ROE_VAL           VARCHAR2(9);  -- ROE(자기자본이익률)
ALTER TABLE TB_STK_MASTER ADD BASE_DT           VARCHAR2(8);  -- 기준년월 (YYYYMM)
ALTER TABLE TB_STK_MASTER ADD PRDY_AVLS_SCAL    VARCHAR2(9);  -- 전일기준시가총액(억)
ALTER TABLE TB_STK_MASTER ADD CO_CD             VARCHAR2(3);  -- 그룹사코드

COMMENT ON COLUMN TB_STK_MASTER.SALE_ACCOUNT   IS '매출액 (단위: 억)';
COMMENT ON COLUMN TB_STK_MASTER.BSOP_PRFI      IS '영업이익 (단위: 억)';
COMMENT ON COLUMN TB_STK_MASTER.OP_PRFI        IS '경상이익 (단위: 억)';
COMMENT ON COLUMN TB_STK_MASTER.THTR_NTIN      IS '당기순이익 (단위: 억)';
COMMENT ON COLUMN TB_STK_MASTER.PRDY_AVLS_SCAL IS '전일기준 시가총액 (단위: 억)';
COMMENT ON COLUMN TB_STK_MASTER.BASE_DT        IS '재무정보 기준년월 (YYYYMM)';
