CREATE TABLE TB_STK_MASTER (
    STK_CD         VARCHAR2(20)  NOT NULL,
    STK_NM         VARCHAR2(100),
    MKT_CD         VARCHAR2(10),
    DOW_MEMBER_YN  CHAR(1)  DEFAULT 'N' NOT NULL,
    STK_STATUS     VARCHAR2(10),
    LIST_DT        DATE,
    DELIST_DT      DATE,
    USE_YN         CHAR(1)  DEFAULT 'Y',
    CREATED_AT     DATE     DEFAULT SYSDATE,
    UPDATED_AT     DATE     DEFAULT SYSDATE,
    CONSTRAINT PK_STK_MASTER PRIMARY KEY (STK_CD)
);

COMMENT ON COLUMN TB_STK_MASTER.MKT_CD IS '상장 시장/거래소: KOSPI, KOSDAQ, NASDAQ, NYSE';
COMMENT ON COLUMN TB_STK_MASTER.DOW_MEMBER_YN IS '다우지수 편입 여부: Y/N';
COMMENT ON COLUMN TB_STK_MASTER.STK_STATUS IS '종목상태: NORMAL/HALT/DELIST/CAUTION';
COMMENT ON COLUMN TB_STK_MASTER.USE_YN IS '추천 대상 포함 여부: Y(포함) / N(제외)';
