PROMPT === TB_REC_SIGNAL memory model migration start ===

DECLARE
    v_cnt NUMBER;
BEGIN
    SELECT COUNT(*)
      INTO v_cnt
      FROM USER_TAB_COLUMNS
     WHERE TABLE_NAME = 'TB_REC_SIGNAL'
       AND COLUMN_NAME = 'MKT_CD';

    IF v_cnt = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE TB_REC_SIGNAL ADD (MKT_CD VARCHAR2(10))';
    END IF;
END;
/

UPDATE TB_REC_SIGNAL
   SET MKT_CD = 'KR'
 WHERE MKT_CD IS NULL;

COMMIT;

DECLARE
    v_nullable VARCHAR2(1);
BEGIN
    SELECT NULLABLE
      INTO v_nullable
      FROM USER_TAB_COLUMNS
     WHERE TABLE_NAME = 'TB_REC_SIGNAL'
       AND COLUMN_NAME = 'MKT_CD';

    IF v_nullable = 'Y' THEN
        EXECUTE IMMEDIATE 'ALTER TABLE TB_REC_SIGNAL MODIFY (MKT_CD VARCHAR2(10) NOT NULL)';
    END IF;
END;
/

DECLARE
    v_data_length NUMBER;
BEGIN
    SELECT DATA_LENGTH
      INTO v_data_length
      FROM USER_TAB_COLUMNS
     WHERE TABLE_NAME = 'TB_BATCH_EXEC_ITEM_LOG'
       AND COLUMN_NAME = 'ERROR_MSG';

    IF v_data_length < 2000 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE TB_BATCH_EXEC_ITEM_LOG MODIFY (ERROR_MSG VARCHAR2(2000))';
    END IF;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        NULL;
END;
/

DECLARE
    v_cnt NUMBER;
BEGIN
    SELECT COUNT(*)
      INTO v_cnt
      FROM USER_CONSTRAINTS
     WHERE TABLE_NAME = 'TB_REC_SIGNAL'
       AND CONSTRAINT_NAME = 'PK_REC_SIGNAL';

    IF v_cnt > 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE TB_REC_SIGNAL DROP CONSTRAINT PK_REC_SIGNAL';
    END IF;
END;
/

ALTER TABLE TB_REC_SIGNAL
    ADD CONSTRAINT PK_REC_SIGNAL PRIMARY KEY (BASE_DT, MKT_CD, STK_CD);

DECLARE
    v_cnt NUMBER;
BEGIN
    SELECT COUNT(*)
      INTO v_cnt
      FROM USER_INDEXES
     WHERE INDEX_NAME = 'IDX_REC_SIGNAL_YN';

    IF v_cnt > 0 THEN
        EXECUTE IMMEDIATE 'DROP INDEX IDX_REC_SIGNAL_YN';
    END IF;
END;
/

CREATE INDEX IDX_REC_SIGNAL_YN
    ON TB_REC_SIGNAL (BASE_DT, MKT_CD, REC_YN);

DECLARE
    v_cnt NUMBER;
BEGIN
    SELECT COUNT(*)
      INTO v_cnt
      FROM USER_TABLES
     WHERE TABLE_NAME = 'TB_BATCH_EXEC_ITEM_LOG';

    IF v_cnt = 0 THEN
        EXECUTE IMMEDIATE q'[
            CREATE TABLE TB_BATCH_EXEC_ITEM_LOG (
                EXEC_ID       VARCHAR2(36)    NOT NULL,
                BATCH_ID      VARCHAR2(50)    NOT NULL,
                BASE_DT       DATE            NOT NULL,
                MKT_CD        VARCHAR2(10)    NOT NULL,
                STK_CD        VARCHAR2(20)    NOT NULL,
                STK_NM        VARCHAR2(100),
                ITEM_STATUS   VARCHAR2(20)    NOT NULL,
                ERROR_MSG     VARCHAR2(400),
                CREATED_AT    DATE DEFAULT SYSDATE,
                UPDATED_AT    DATE DEFAULT SYSDATE,
                CONSTRAINT PK_BATCH_EXEC_ITEM_LOG PRIMARY KEY (EXEC_ID, STK_CD)
            )
        ]';
    END IF;
END;
/

DECLARE
    v_cnt NUMBER;
BEGIN
    SELECT COUNT(*)
      INTO v_cnt
      FROM USER_INDEXES
     WHERE INDEX_NAME = 'IDX_BATCH_EXEC_ITEM_LOG_1';

    IF v_cnt = 0 THEN
        EXECUTE IMMEDIATE 'CREATE INDEX IDX_BATCH_EXEC_ITEM_LOG_1 ON TB_BATCH_EXEC_ITEM_LOG (BATCH_ID, BASE_DT, MKT_CD, ITEM_STATUS)';
    END IF;
END;
/

PROMPT === TB_REC_SIGNAL memory model migration done ===
