-- 일부 컬럼만 먼저 반영된 운영 DB에서도 누락 컬럼만 개별 보강되도록 분리한다.
ALTER TABLE TB_S_POSITION ADD (SOURCE_PICK_ID NUMBER);
ALTER TABLE TB_S_POSITION ADD (BUY_DATE DATE);
ALTER TABLE TB_S_POSITION ADD (TARGET_PRICE NUMBER(18,4));
ALTER TABLE TB_S_POSITION ADD (STOP_PRICE NUMBER(18,4));
ALTER TABLE TB_S_POSITION ADD (TP1_PRICE NUMBER(18,4));
ALTER TABLE TB_S_POSITION ADD (SELL_GUIDE_STATE VARCHAR2(20));
ALTER TABLE TB_S_POSITION ADD (LAST_SELL_SIGNAL_CODE VARCHAR2(30));
ALTER TABLE TB_S_POSITION ADD (LAST_TRACK_DATE DATE);

DROP INDEX UX_TB_S_POSITION_01;
CREATE UNIQUE INDEX UX_TB_S_POSITION_01 ON TB_S_POSITION (STOCK_GROUP, STOCK_CODE, CLOSE_FLAG);
CREATE INDEX IX_TB_S_POSITION_04 ON TB_S_POSITION (SOURCE_PICK_ID);
CREATE INDEX IX_TB_S_POSITION_05 ON TB_S_POSITION (SELL_GUIDE_STATE, LAST_TRACK_DATE);
