PROMPT === TB_REC_SIGNAL list partition migration start ===
SET SERVEROUTPUT ON

DECLARE
    v_exists NUMBER;
    v_partitioned VARCHAR2(3);
BEGIN
    SELECT COUNT(*)
      INTO v_exists
      FROM USER_TABLES
     WHERE TABLE_NAME = 'TB_REC_SIGNAL';

    IF v_exists = 0 THEN
        RAISE_APPLICATION_ERROR(-20001, 'TB_REC_SIGNAL not found');
    END IF;

    SELECT PARTITIONED
      INTO v_partitioned
      FROM USER_TABLES
     WHERE TABLE_NAME = 'TB_REC_SIGNAL';

    IF v_partitioned = 'YES' THEN
        DBMS_OUTPUT.PUT_LINE('SKIP: TB_REC_SIGNAL is already partitioned');
        RETURN;
    END IF;

    SELECT COUNT(*)
      INTO v_exists
      FROM USER_TABLES
     WHERE TABLE_NAME = 'TB_REC_SIGNAL_PNEW';

    IF v_exists > 0 THEN
        RAISE_APPLICATION_ERROR(-20002, 'TB_REC_SIGNAL_PNEW already exists');
    END IF;

    SELECT COUNT(*)
      INTO v_exists
      FROM USER_TABLES
     WHERE TABLE_NAME = 'TB_REC_SIGNAL_BAK_20260406';

    IF v_exists > 0 THEN
        RAISE_APPLICATION_ERROR(-20003, 'TB_REC_SIGNAL_BAK_20260406 already exists');
    END IF;
END;
/

PROMPT [BEFORE] ROW COUNT BY MARKET
SELECT NVL(MKT_CD, 'NULL') AS MKT_CD,
       COUNT(*) AS ROW_CNT
  FROM TB_REC_SIGNAL
 GROUP BY MKT_CD
 ORDER BY MKT_CD;

CREATE TABLE TB_REC_SIGNAL_PNEW (
    BASE_DT          DATE           NOT NULL,
    MKT_CD           VARCHAR2(10)   NOT NULL,
    STK_CD           VARCHAR2(20)   NOT NULL,
    STK_NM           VARCHAR2(100),
    CUR_PRICE        NUMBER(18,4),
    MON_OPEN_PRICE   NUMBER(18,4),
    MA5              NUMBER(18,4),
    MA20             NUMBER(18,4),
    MA60             NUMBER(18,4),
    MA120            NUMBER(18,4),
    MA240            NUMBER(18,4),
    GOLDEN_YN        CHAR(1),
    MON_UP_YN        CHAR(1),
    MON_CHG_RATE     NUMBER(18,4),
    TREND_STRENGTH   NUMBER(18,4),
    AVG_TRD_VAL_20   NUMBER(18,0),
    REC_YN           CHAR(1),
    REC_GRADE        VARCHAR2(1),
    REC_REASON       VARCHAR2(400),
    CREATED_AT       DATE DEFAULT SYSDATE,
    UPDATED_AT       DATE DEFAULT SYSDATE,
    CONSTRAINT PK_REC_SIGNAL_PNEW PRIMARY KEY (BASE_DT, MKT_CD, STK_CD)
        USING INDEX LOCAL
)
PARTITION BY LIST (MKT_CD) (
    PARTITION P_KR VALUES ('KR'),
    PARTITION P_US VALUES ('US'),
    PARTITION P_ETC VALUES (DEFAULT)
);

COMMENT ON COLUMN TB_REC_SIGNAL_PNEW.BASE_DT IS 'EFFECTIVE_BASE_DATE (실제 거래일 기준)';
COMMENT ON COLUMN TB_REC_SIGNAL_PNEW.MKT_CD IS '시장그룹: KR / US';
COMMENT ON COLUMN TB_REC_SIGNAL_PNEW.MON_OPEN_PRICE IS 'EFFECTIVE_YYYYMM 첫 거래일 ADJ_OPEN_PRICE';
COMMENT ON COLUMN TB_REC_SIGNAL_PNEW.REC_GRADE IS '추천등급: A/B/C. REC_YN=N 이면 NULL 저장';
COMMENT ON COLUMN TB_REC_SIGNAL_PNEW.AVG_TRD_VAL_20 IS '최근 20거래일 평균 거래대금';

CREATE INDEX IDX_REC_SIGNAL_YN_PNEW
    ON TB_REC_SIGNAL_PNEW (BASE_DT, MKT_CD, REC_YN)
    LOCAL;

INSERT /*+ APPEND */ INTO TB_REC_SIGNAL_PNEW (
    BASE_DT,
    MKT_CD,
    STK_CD,
    STK_NM,
    CUR_PRICE,
    MON_OPEN_PRICE,
    MA5,
    MA20,
    MA60,
    MA120,
    MA240,
    GOLDEN_YN,
    MON_UP_YN,
    MON_CHG_RATE,
    TREND_STRENGTH,
    AVG_TRD_VAL_20,
    REC_YN,
    REC_GRADE,
    REC_REASON,
    CREATED_AT,
    UPDATED_AT
)
SELECT BASE_DT,
       MKT_CD,
       STK_CD,
       STK_NM,
       CUR_PRICE,
       MON_OPEN_PRICE,
       MA5,
       MA20,
       MA60,
       MA120,
       MA240,
       GOLDEN_YN,
       MON_UP_YN,
       MON_CHG_RATE,
       TREND_STRENGTH,
       AVG_TRD_VAL_20,
       REC_YN,
       REC_GRADE,
       REC_REASON,
       CREATED_AT,
       UPDATED_AT
  FROM TB_REC_SIGNAL;

COMMIT;

DECLARE
    v_old_cnt NUMBER;
    v_new_cnt NUMBER;
BEGIN
    SELECT COUNT(*)
      INTO v_old_cnt
      FROM TB_REC_SIGNAL;

    SELECT COUNT(*)
      INTO v_new_cnt
      FROM TB_REC_SIGNAL_PNEW;

    IF v_old_cnt != v_new_cnt THEN
        RAISE_APPLICATION_ERROR(-20004, 'row count mismatch old=' || v_old_cnt || ' new=' || v_new_cnt);
    END IF;
END;
/

PROMPT [VERIFY] PARTITIONED NEW TABLE
SELECT PARTITIONED
  FROM USER_TABLES
 WHERE TABLE_NAME = 'TB_REC_SIGNAL_PNEW';

PROMPT [VERIFY] NEW ROW COUNT BY MARKET
SELECT NVL(MKT_CD, 'NULL') AS MKT_CD,
       COUNT(*) AS ROW_CNT
  FROM TB_REC_SIGNAL_PNEW
 GROUP BY MKT_CD
 ORDER BY MKT_CD;

ALTER TABLE TB_REC_SIGNAL RENAME TO TB_REC_SIGNAL_BAK_20260406;

DECLARE
    v_exists NUMBER;
BEGIN
    SELECT COUNT(*)
      INTO v_exists
      FROM USER_CONSTRAINTS
     WHERE TABLE_NAME = 'TB_REC_SIGNAL_BAK_20260406'
       AND CONSTRAINT_NAME = 'PK_REC_SIGNAL';

    IF v_exists > 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE TB_REC_SIGNAL_BAK_20260406 RENAME CONSTRAINT PK_REC_SIGNAL TO PK_REC_SIGNAL_BAK_20260406';
    END IF;
END;
/

DECLARE
    v_exists NUMBER;
BEGIN
    SELECT COUNT(*)
      INTO v_exists
      FROM USER_INDEXES
     WHERE INDEX_NAME = 'PK_REC_SIGNAL';

    IF v_exists > 0 THEN
        EXECUTE IMMEDIATE 'ALTER INDEX PK_REC_SIGNAL RENAME TO PK_REC_SIGNAL_BAK_20260406';
    END IF;
END;
/

DECLARE
    v_exists NUMBER;
BEGIN
    SELECT COUNT(*)
      INTO v_exists
      FROM USER_INDEXES
     WHERE INDEX_NAME = 'IDX_REC_SIGNAL_YN';

    IF v_exists > 0 THEN
        EXECUTE IMMEDIATE 'ALTER INDEX IDX_REC_SIGNAL_YN RENAME TO IDX_REC_SIGNAL_YN_BAK_20260406';
    END IF;
END;
/

ALTER TABLE TB_REC_SIGNAL_PNEW RENAME TO TB_REC_SIGNAL;
ALTER TABLE TB_REC_SIGNAL RENAME CONSTRAINT PK_REC_SIGNAL_PNEW TO PK_REC_SIGNAL;
ALTER INDEX PK_REC_SIGNAL_PNEW RENAME TO PK_REC_SIGNAL;
ALTER INDEX IDX_REC_SIGNAL_YN_PNEW RENAME TO IDX_REC_SIGNAL_YN;

BEGIN
    DBMS_STATS.GATHER_TABLE_STATS(
        OWNNAME => USER,
        TABNAME => 'TB_REC_SIGNAL',
        GRANULARITY => 'ALL'
    );
END;
/

PROMPT [AFTER] PARTITION INFO
SELECT PARTITION_NAME,
       NUM_ROWS
  FROM USER_TAB_PARTITIONS
 WHERE TABLE_NAME = 'TB_REC_SIGNAL'
 ORDER BY PARTITION_POSITION;

PROMPT [AFTER] ROW COUNT BY MARKET
SELECT NVL(MKT_CD, 'NULL') AS MKT_CD,
       COUNT(*) AS ROW_CNT
  FROM TB_REC_SIGNAL
 GROUP BY MKT_CD
 ORDER BY MKT_CD;

PROMPT [AFTER] SEGMENT SIZE (MB)
SELECT SEGMENT_NAME,
       SEGMENT_TYPE,
       ROUND(BYTES / 1024 / 1024, 2) AS MB
  FROM USER_SEGMENTS
 WHERE SEGMENT_NAME IN (
       'TB_REC_SIGNAL',
       'PK_REC_SIGNAL',
       'IDX_REC_SIGNAL_YN',
       'TB_REC_SIGNAL_BAK_20260406',
       'PK_REC_SIGNAL_BAK_20260406',
       'IDX_REC_SIGNAL_YN_BAK_20260406'
 )
 ORDER BY BYTES DESC;

PROMPT === TB_REC_SIGNAL list partition migration done ===
