PROMPT === TB_STK_MASTER 세분화 컬럼 추가 migration start ===
PROMPT    STK_NM_EN, SECTOR_CD, MKT_CAP_SIZE, PREF_YN, SETTLE_MONTH, CURRENCY

-- 1. STK_NM_EN: 영문종목명 (해외주식 English name)
DECLARE
    v_cnt NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_cnt FROM USER_TAB_COLUMNS
     WHERE TABLE_NAME = 'TB_STK_MASTER' AND COLUMN_NAME = 'STK_NM_EN';
    IF v_cnt = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE TB_STK_MASTER ADD STK_NM_EN VARCHAR2(200) DEFAULT NULL';
        DBMS_OUTPUT.PUT_LINE('STK_NM_EN 추가 완료');
    ELSE
        DBMS_OUTPUT.PUT_LINE('STK_NM_EN 이미 존재 — skip');
    END IF;
END;
/
COMMENT ON COLUMN TB_STK_MASTER.STK_NM_EN IS '영문종목명 (해외주식 .cod English name)';

-- 2. SECTOR_CD: 업종대분류코드 (국내주식 지수업종대분류 4자리)
DECLARE
    v_cnt NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_cnt FROM USER_TAB_COLUMNS
     WHERE TABLE_NAME = 'TB_STK_MASTER' AND COLUMN_NAME = 'SECTOR_CD';
    IF v_cnt = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE TB_STK_MASTER ADD SECTOR_CD VARCHAR2(6) DEFAULT NULL';
        DBMS_OUTPUT.PUT_LINE('SECTOR_CD 추가 완료');
    ELSE
        DBMS_OUTPUT.PUT_LINE('SECTOR_CD 이미 존재 — skip');
    END IF;
END;
/
COMMENT ON COLUMN TB_STK_MASTER.SECTOR_CD IS '업종대분류코드 (KOSPI/KOSDAQ .mst 지수업종대분류, 4자리)';

-- 3. MKT_CAP_SIZE: 시가총액규모구분 (1=대형 2=중형 3=소형)
DECLARE
    v_cnt NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_cnt FROM USER_TAB_COLUMNS
     WHERE TABLE_NAME = 'TB_STK_MASTER' AND COLUMN_NAME = 'MKT_CAP_SIZE';
    IF v_cnt = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE TB_STK_MASTER ADD MKT_CAP_SIZE CHAR(1) DEFAULT NULL';
        DBMS_OUTPUT.PUT_LINE('MKT_CAP_SIZE 추가 완료');
    ELSE
        DBMS_OUTPUT.PUT_LINE('MKT_CAP_SIZE 이미 존재 — skip');
    END IF;
END;
/
COMMENT ON COLUMN TB_STK_MASTER.MKT_CAP_SIZE IS '시가총액규모구분: 1=대형, 2=중형, 3=소형 (KOSPI/KOSDAQ)';

-- 4. PREF_YN: 우선주여부 (Y=우선주, N=보통주)
DECLARE
    v_cnt NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_cnt FROM USER_TAB_COLUMNS
     WHERE TABLE_NAME = 'TB_STK_MASTER' AND COLUMN_NAME = 'PREF_YN';
    IF v_cnt = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE TB_STK_MASTER ADD PREF_YN CHAR(1) DEFAULT ''N'' NOT NULL';
        DBMS_OUTPUT.PUT_LINE('PREF_YN 추가 완료');
    ELSE
        DBMS_OUTPUT.PUT_LINE('PREF_YN 이미 존재 — skip');
    END IF;
END;
/
COMMENT ON COLUMN TB_STK_MASTER.PREF_YN IS '우선주여부: Y=우선주, N=보통주 (KOSPI/KOSDAQ .mst 우선주구분코드)';

-- 5. SETTLE_MONTH: 결산월 (01~12)
DECLARE
    v_cnt NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_cnt FROM USER_TAB_COLUMNS
     WHERE TABLE_NAME = 'TB_STK_MASTER' AND COLUMN_NAME = 'SETTLE_MONTH';
    IF v_cnt = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE TB_STK_MASTER ADD SETTLE_MONTH VARCHAR2(2) DEFAULT NULL';
        DBMS_OUTPUT.PUT_LINE('SETTLE_MONTH 추가 완료');
    ELSE
        DBMS_OUTPUT.PUT_LINE('SETTLE_MONTH 이미 존재 — skip');
    END IF;
END;
/
COMMENT ON COLUMN TB_STK_MASTER.SETTLE_MONTH IS '결산월 (01~12, KOSPI/KOSDAQ .mst)';

-- 6. CURRENCY: 통화코드 (해외주식 USD/HKD 등)
DECLARE
    v_cnt NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_cnt FROM USER_TAB_COLUMNS
     WHERE TABLE_NAME = 'TB_STK_MASTER' AND COLUMN_NAME = 'CURRENCY';
    IF v_cnt = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE TB_STK_MASTER ADD CURRENCY VARCHAR2(10) DEFAULT NULL';
        DBMS_OUTPUT.PUT_LINE('CURRENCY 추가 완료');
    ELSE
        DBMS_OUTPUT.PUT_LINE('CURRENCY 이미 존재 — skip');
    END IF;
END;
/
COMMENT ON COLUMN TB_STK_MASTER.CURRENCY IS '통화코드 (해외주식 .cod currency: USD, HKD 등)';

COMMIT;

PROMPT === TB_STK_MASTER 세분화 컬럼 추가 migration done ===
PROMPT    추가된 컬럼: STK_NM_EN, SECTOR_CD, MKT_CAP_SIZE, PREF_YN, SETTLE_MONTH, CURRENCY
