-- WF-2-4 상태머신 임계값 튜닝용 데모 데이터(비파괴)
-- 주의: STOCK_GROUP='WF_TUNE_DEMO'로만 적재. 기존 실데이터 건드리지 않음.

-- 1) 포지션 스냅샷 데모 적재
INSERT INTO TB_S_POSITION (STOCK_GROUP, STOCK_CODE, MARKET_CODE, TOTAL_QTY, AVG_PRICE, CLOSE_FLAG, STATE_CODE, MODIFY_DATE, CREATE_USER, CREATE_DATE)
SELECT 'WF_TUNE_DEMO', '005930', 'KR', 10, 70000, 'N', 'HOLD', SYSDATE, 'SYSTEM', SYSDATE FROM DUAL
WHERE NOT EXISTS (
  SELECT 1 FROM TB_S_POSITION WHERE STOCK_GROUP='WF_TUNE_DEMO' AND STOCK_CODE='005930'
);

INSERT INTO TB_S_POSITION (STOCK_GROUP, STOCK_CODE, MARKET_CODE, TOTAL_QTY, AVG_PRICE, CLOSE_FLAG, STATE_CODE, MODIFY_DATE, CREATE_USER, CREATE_DATE)
SELECT 'WF_TUNE_DEMO', '000660', 'KR', 8, 120000, 'N', 'HOLD', SYSDATE, 'SYSTEM', SYSDATE FROM DUAL
WHERE NOT EXISTS (
  SELECT 1 FROM TB_S_POSITION WHERE STOCK_GROUP='WF_TUNE_DEMO' AND STOCK_CODE='000660'
);

-- 2) 트랜잭션 데모 적재
INSERT INTO TB_S_POSITION_TXN (POSITION_ID, STOCK_GROUP, STOCK_CODE, ACTION_TYPE, QTY, PRICE, BEFORE_QTY, BEFORE_AVG, AFTER_QTY, AFTER_AVG, REASON_TEXT, JSON_PARAMS, CREATE_USER, CREATE_DATE)
VALUES (NULL, 'WF_TUNE_DEMO', '005930', 'ADD', 10, 70000, 0, 0, 10, 70000, 'seed add', '{"event_type":"ENTER","action_type":"ADD","qty":"10","price":"70000","after_qty":10,"after_avg":70000,"pnl_pct":0.00}', 'SYSTEM', SYSDATE-2);

INSERT INTO TB_S_POSITION_TXN (POSITION_ID, STOCK_GROUP, STOCK_CODE, ACTION_TYPE, QTY, PRICE, BEFORE_QTY, BEFORE_AVG, AFTER_QTY, AFTER_AVG, REASON_TEXT, JSON_PARAMS, CREATE_USER, CREATE_DATE)
VALUES (NULL, 'WF_TUNE_DEMO', '005930', 'AVERAGE_DOWN', 5, 67000, 10, 70000, 15, 69000, 'seed avg down', '{"event_type":"AVERAGE_DOWN","action_type":"AVERAGE_DOWN","qty":"5","price":"67000","after_qty":15,"after_avg":69000,"pnl_pct":-2.90}', 'SYSTEM', SYSDATE-1.5);

INSERT INTO TB_S_POSITION_TXN (POSITION_ID, STOCK_GROUP, STOCK_CODE, ACTION_TYPE, QTY, PRICE, BEFORE_QTY, BEFORE_AVG, AFTER_QTY, AFTER_AVG, REASON_TEXT, JSON_PARAMS, CREATE_USER, CREATE_DATE)
VALUES (NULL, 'WF_TUNE_DEMO', '000660', 'ADD', 8, 120000, 0, 0, 8, 120000, 'seed add', '{"event_type":"ENTER","action_type":"ADD","qty":"8","price":"120000","after_qty":8,"after_avg":120000,"pnl_pct":0.00}', 'SYSTEM', SYSDATE-2);

-- 3) 이벤트 데모 적재 (임계값 근처/넘김 포함)
INSERT INTO TB_S_POSITION_EVENT (POSITION_ID, STOCK_GROUP, STOCK_CODE, EVENT_TYPE, EVENT_LEVEL, EVENT_TIME, MESSAGE, JSON_PARAMS, SOURCE_TXN_ID, CREATE_DATE)
VALUES (NULL, 'WF_TUNE_DEMO', '005930', 'ENTER', 'INFO', SYSDATE-2, '[ENTER] action=ADD', '{"event_type":"ENTER","action_type":"ADD","qty":"10","price":"70000","after_qty":10,"after_avg":70000,"pnl_pct":0.00}', NULL, SYSDATE-2);

INSERT INTO TB_S_POSITION_EVENT (POSITION_ID, STOCK_GROUP, STOCK_CODE, EVENT_TYPE, EVENT_LEVEL, EVENT_TIME, MESSAGE, JSON_PARAMS, SOURCE_TXN_ID, CREATE_DATE)
VALUES (NULL, 'WF_TUNE_DEMO', '005930', 'RISK_OFF', 'WARN', SYSDATE-1.8, '[RISK_OFF] near threshold', '{"event_type":"RISK_OFF","action_type":"ADD","qty":"10","price":"67800","after_qty":10,"after_avg":70000,"pnl_pct":-3.14}', NULL, SYSDATE-1.8);

INSERT INTO TB_S_POSITION_EVENT (POSITION_ID, STOCK_GROUP, STOCK_CODE, EVENT_TYPE, EVENT_LEVEL, EVENT_TIME, MESSAGE, JSON_PARAMS, SOURCE_TXN_ID, CREATE_DATE)
VALUES (NULL, 'WF_TUNE_DEMO', '005930', 'AVERAGE_DOWN', 'INFO', SYSDATE-1.5, '[AVERAGE_DOWN] rebalance', '{"event_type":"AVERAGE_DOWN","action_type":"AVERAGE_DOWN","qty":"5","price":"67000","after_qty":15,"after_avg":69000,"pnl_pct":-2.90}', NULL, SYSDATE-1.5);

INSERT INTO TB_S_POSITION_EVENT (POSITION_ID, STOCK_GROUP, STOCK_CODE, EVENT_TYPE, EVENT_LEVEL, EVENT_TIME, MESSAGE, JSON_PARAMS, SOURCE_TXN_ID, CREATE_DATE)
VALUES (NULL, 'WF_TUNE_DEMO', '005930', 'TREND_FOLLOW', 'INFO', SYSDATE-1.2, '[TREND_FOLLOW] breakout', '{"event_type":"TREND_FOLLOW","action_type":"ADD","qty":"3","price":"70000","after_qty":18,"after_avg":69100,"pnl_pct":1.30}', NULL, SYSDATE-1.2);

INSERT INTO TB_S_POSITION_EVENT (POSITION_ID, STOCK_GROUP, STOCK_CODE, EVENT_TYPE, EVENT_LEVEL, EVENT_TIME, MESSAGE, JSON_PARAMS, SOURCE_TXN_ID, CREATE_DATE)
VALUES (NULL, 'WF_TUNE_DEMO', '000660', 'ENTER', 'INFO', SYSDATE-2, '[ENTER] action=ADD', '{"event_type":"ENTER","action_type":"ADD","qty":"8","price":"120000","after_qty":8,"after_avg":120000,"pnl_pct":0.00}', NULL, SYSDATE-2);

INSERT INTO TB_S_POSITION_EVENT (POSITION_ID, STOCK_GROUP, STOCK_CODE, EVENT_TYPE, EVENT_LEVEL, EVENT_TIME, MESSAGE, JSON_PARAMS, SOURCE_TXN_ID, CREATE_DATE)
VALUES (NULL, 'WF_TUNE_DEMO', '000660', 'RISK_OFF', 'WARN', SYSDATE-1.0, '[RISK_OFF] deep loss', '{"event_type":"RISK_OFF","action_type":"ADD","qty":"8","price":"114000","after_qty":8,"after_avg":120000,"pnl_pct":-5.00}', NULL, SYSDATE-1.0);

COMMIT;
