-- WF-3-8 이력 검증 쿼리
-- 사용법: SQL*Plus / SQL Developer에서 실행

-- 1) 최근 포지션 스냅샷
SELECT POSITION_ID, STOCK_GROUP, STOCK_CODE, TOTAL_QTY, AVG_PRICE, CLOSE_FLAG, STATE_CODE, MODIFY_DATE
  FROM TB_S_POSITION
 ORDER BY MODIFY_DATE DESC
 FETCH FIRST 100 ROWS ONLY;

-- 2) 최근 거래 이력(TXN)
SELECT TXN_ID, STOCK_GROUP, STOCK_CODE, ACTION_TYPE, QTY, PRICE,
       AFTER_QTY, AFTER_AVG, CREATE_USER, CREATE_DATE
  FROM TB_S_POSITION_TXN
 ORDER BY CREATE_DATE DESC
 FETCH FIRST 200 ROWS ONLY;

-- 3) 최근 이벤트 이력(EVENT)
SELECT EVENT_ID, STOCK_GROUP, STOCK_CODE, EVENT_TYPE, EVENT_LEVEL, MESSAGE, EVENT_TIME
  FROM TB_S_POSITION_EVENT
 ORDER BY EVENT_TIME DESC
 FETCH FIRST 200 ROWS ONLY;

-- 4) 종목별 상태 일관성 점검(스냅샷 vs 최근 이벤트)
SELECT p.STOCK_GROUP,
       p.STOCK_CODE,
       p.TOTAL_QTY,
       p.STATE_CODE,
       p.CLOSE_FLAG,
       e.EVENT_TYPE AS LAST_EVENT_TYPE,
       e.EVENT_TIME AS LAST_EVENT_TIME
  FROM TB_S_POSITION p
  LEFT JOIN (
        SELECT STOCK_GROUP, STOCK_CODE,
               MAX(EVENT_TIME) AS LAST_EVENT_TIME
          FROM TB_S_POSITION_EVENT
         GROUP BY STOCK_GROUP, STOCK_CODE
  ) le
    ON p.STOCK_GROUP = le.STOCK_GROUP
   AND p.STOCK_CODE = le.STOCK_CODE
  LEFT JOIN TB_S_POSITION_EVENT e
    ON e.STOCK_GROUP = le.STOCK_GROUP
   AND e.STOCK_CODE = le.STOCK_CODE
   AND e.EVENT_TIME = le.LAST_EVENT_TIME
 ORDER BY p.MODIFY_DATE DESC;

-- 5) 이상치 탐지: CLOSE_FLAG='Y'인데 수량이 남아있는 케이스
SELECT *
  FROM TB_S_POSITION
 WHERE CLOSE_FLAG = 'Y'
   AND NVL(TOTAL_QTY,0) > 0;

-- 6) 이상치 탐지: 이벤트 없이 거래만 있는 케이스(최근 1일)
SELECT t.STOCK_GROUP, t.STOCK_CODE, COUNT(*) TXN_CNT
  FROM TB_S_POSITION_TXN t
 WHERE t.CREATE_DATE >= SYSDATE - 1
   AND NOT EXISTS (
       SELECT 1
         FROM TB_S_POSITION_EVENT e
        WHERE e.STOCK_GROUP = t.STOCK_GROUP
          AND e.STOCK_CODE = t.STOCK_CODE
          AND e.EVENT_TIME >= t.CREATE_DATE - (1/24)
          AND e.EVENT_TIME <= t.CREATE_DATE + (1/24)
   )
 GROUP BY t.STOCK_GROUP, t.STOCK_CODE
 ORDER BY TXN_CNT DESC;
