SELECT PICK_ID, SOURCE_BASE_DT, SOURCE_MKT_CD, STK_CD, PICK_STATUS, WATCH_GROUP_ID, POSITION_ID, WATCH_SAVED_AT
  FROM TB_S_RECO_PICK
 ORDER BY CREATE_DATE DESC
 FETCH FIRST 100 ROWS ONLY;

SELECT PICK_ID, TRADE_DT, STK_CD, CLOSE_PRICE, RETURN_FROM_WATCH_PCT, RETURN_FROM_BUY_PCT, SELL_SIGNAL_CODE
  FROM TB_S_RECO_PICK_DAILY
 ORDER BY TRADE_DT DESC, PICK_ID DESC
 FETCH FIRST 200 ROWS ONLY;

SELECT PICK_ID, EVAL_TYPE, HOLD_DAYS, RETURN_PCT, MFE_PCT, MAE_PCT, WIN_YN, CALC_STATUS
  FROM TB_S_RECO_PICK_EVAL
 ORDER BY MODIFY_DATE DESC
 FETCH FIRST 200 ROWS ONLY;

SELECT *
  FROM VW_S_RECO_PICK_STATS
 ORDER BY HOLD_DAYS, SAMPLE_CNT DESC
 FETCH FIRST 100 ROWS ONLY;
