#KIS AppToken auto updated
#Wed Mar 04 21:32:21 KST 2026
kis.watchlist.domestic.realtime.enabled=false
kis.env=real
kis.account.no=6820546701
kis.rest.limit.per.second=20
kis.watchlist.quote.period.ms=500
kis.app.secret=DQsgBCi5yEJajPswCS8gY1ipi3UuRuHGfqBzyv2M9exvR1hx5fZhjWwL/Uhzv8QMB6NF0FSs7rerlCOG/6tPjWVuUrjSdAuCEUS4Ecw+Okaa+wI/t8jJ27eEZW/PMooZZ39njo0LDT/XHrkAOIYTJ9DQWLUkgaGlVafiDb8R3swRGqcuet4\=
kis.socket.limit.per.second=10
kis.app.tokenKey=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0b2tlbiIsImF1ZCI6ImM1M2MyYTEyLTVlNzQtNDI4MS05MTY0LWI5Y2IwOGY2Y2EwNiIsInByZHRfY2QiOiIiLCJpc3MiOiJ1bm9ndyIsImV4cCI6MTc3MjcwNDQ4OSwiaWF0IjoxNzcyNjE4MDg5LCJqdGkiOiJQU0RuMXhzUkNvdE1KdUlnV0F3T2VMQTFTZ01tbkxoVVlZMlUifQ.zJmx8ESkzpK3Zm1n5cxKBPnLJeBhI5jYoaYJesLPz2CFq_YTfBvuZAg6j8lTDgFsuCZkSf8QNjsEphRzFpyICw
kis.app.tokenExpire=20251204101530
kis.socket.host=ws\://ops.koreainvestment.com\:21000
kis.account.product.code=01
kis.app.tokenExpiredAt=2026-03-05 18\:54\:49
kis.http.host=https\://openapi.koreainvestment.com\:9443
kis.app.key=PSDn1xsRCotMJuIgWAwOeLA1SgMmnLhUYY2U
