#KIS AppToken auto updated
#Thu Mar 05 18:44:49 KST 2026
kis.watchlist.domestic.realtime.enabled=false
kis.env=real
kis.account.no=6820546701
kis.rest.limit.per.second=20
kis.watchlist.quote.period.ms=500
kis.app.secret=DQsgBCi5yEJajPswCS8gY1ipi3UuRuHGfqBzyv2M9exvR1hx5fZhjWwL/Uhzv8QMB6NF0FSs7rerlCOG/6tPjWVuUrjSdAuCEUS4Ecw+Okaa+wI/t8jJ27eEZW/PMooZZ39njo0LDT/XHrkAOIYTJ9DQWLUkgaGlVafiDb8R3swRGqcuet4\=
kis.socket.limit.per.second=10
kis.app.tokenKey=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0b2tlbiIsImF1ZCI6ImEyZGJhYTRmLTNkZmUtNGYwYy04ZGJiLWYwZjIxYTZlZDc0MSIsInByZHRfY2QiOiIiLCJpc3MiOiJ1bm9ndyIsImV4cCI6MTc3Mjc3MTA0NSwiaWF0IjoxNzcyNjg0NjQ1LCJqdGkiOiJQU0RuMXhzUkNvdE1KdUlnV0F3T2VMQTFTZ01tbkxoVVlZMlUifQ.c1KBvqHTmmk2f7qsENxv0p-ADiyCZU9LWEPwSt_immoifHvLSUFWC8GQZT0LYN-kg1i7Zp0ruCtIQsvZ0kYppA
kis.app.tokenExpire=20251204101530
kis.socket.host=ws\://ops.koreainvestment.com\:21000
kis.account.product.code=01
kis.app.tokenExpiredAt=2026-03-06 13\:24\:05
kis.http.host=https\://openapi.koreainvestment.com\:9443
kis.app.key=PSDn1xsRCotMJuIgWAwOeLA1SgMmnLhUYY2U
