#KIS AppToken auto updated
#Sun Feb 15 14:01:42 KST 2026
kis.account.no=6820546701
kis.account.product.code=01
kis.app.key=PSDn1xsRCotMJuIgWAwOeLA1SgMmnLhUYY2U
kis.app.secret=DQsgBCi5yEJajPswCS8gY1ipi3UuRuHGfqBzyv2M9exvR1hx5fZhjWwL/Uhzv8QMB6NF0FSs7rerlCOG/6tPjWVuUrjSdAuCEUS4Ecw+Okaa+wI/t8jJ27eEZW/PMooZZ39njo0LDT/XHrkAOIYTJ9DQWLUkgaGlVafiDb8R3swRGqcuet4\=
kis.app.tokenExpire=20251204101530
kis.app.tokenExpiredAt=2026-02-16 14\:01\:42
kis.app.tokenKey=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0b2tlbiIsImF1ZCI6ImVmMTU1Y2ZiLTRmOWUtNGIyNi1iMGQ4LWQyNTRkNDU3ZDJmYSIsInByZHRfY2QiOiIiLCJpc3MiOiJ1bm9ndyIsImV4cCI6MTc3MTIxODEwMiwiaWF0IjoxNzcxMTMxNzAyLCJqdGkiOiJQU0RuMXhzUkNvdE1KdUlnV0F3T2VMQTFTZ01tbkxoVVlZMlUifQ.I94keBG5XYYe3qPlsAtwTpR9MB6WToiK_9vrpUrQmBV97bABxeKvvWZHP63VIlLJ8oqto8oYXkpYZiY8YrueJA
kis.env=real
kis.http.host=https\://openapi.koreainvestment.com\:9443
kis.rest.limit.per.second=20
kis.socket.host=ws\://ops.koreainvestment.com\:21000
kis.socket.limit.per.second=10
kis.watchlist.domestic.realtime.enabled=false
kis.watchlist.quote.period.ms=500
