#########################################
#	eai server Info
#########################################
mo.server.list=hsheada1
mo.server.remote=hshsoda1
mo.server.protocol=https
mo.server.port=7000

#########################################
#	TIBCO Install DIR  : DATA_FILES_DIV
#########################################
file.os.win.root=C:\\tibco
file.os.order.root=/package/tibco

#########################################
#	TIBCO Application Log dir  : APPLICATION_LOG_ROOT
#########################################
#file.application.log.root=/logs/tibco/application
file.application.log.root=C:\\Users\\GIJ02094\\Desktop\\EAILog\\

#########################################
#	TIBCO Products(Engine,Adpater,EMS Queue) List  : PRODUCTS_LIST_ROOT
#########################################
#file.products.list.root=/logs/scheduler/monitoring/logs/
file.products.list.root=C:\\tibcoMonitoring\\logs\\

#########################################
#	Monitoring Shell Script
#########################################
#shell.monitoring.root=/package/scheduler/scripts/monitoring_script/
shell.monitoring.root=C:\\tibcoMonitoring\\scripts\\

#########################################
#	TIBCO EMS Set
#########################################
mom.ems.user=
mom.ems.pass=
mom.ems.url=

#########################################
#	TIBCO Hawk Config Set
#########################################
hawk.domain.hostName = 
hawk.domain.name = 
hawk.domain.rvDaemon = 
hawk.domain.rvNetwork = 
hawk.domain.rvService = 
hawk.domain.minNum = 1

#########################################
#	EAI Log DB TableSpace Check
#########################################
#PROD
#sub.db.driver=oracle.jdbc.driver.OracleDriver
#sub.db.url=
#sub.db.id=
#sub.db.passwd=
#QAS
sub.db.driver=oracle.jdbc.driver.OracleDriver
sub.db.url=
sub.db.id=
sub.db.passwd=

